---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-certs-config
data:
  instances.yml: |
    instances:
    - name: "elasticsearch"
    - name: "enrichment-bootstrap"
    - name: "kibana"
    - name: "logstash"