---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-elasticsearch-yaml-config
data:
  elasticsearch.yml: |
    cluster.name: "k8s-logs"
    node.name: "${NODE_NAME}"
    network.host: "0.0.0.0"
    discovery.seed_hosts: "${DISCOVERY_SEED_HOSTS}"
    cluster.initial_master_nodes: "${CLUSTER_INITIAL_MASTER_NODES}"
    xpack.monitoring.collection.enabled: "true"
    xpack.license.self_generated.type: "trial"
    xpack.security.enabled: "${XPACK_SECURITY_ENABLED}"
    xpack.security.http.ssl.enabled: "${XPACK_SECURITY_HTTP_SSL_ENABLED}"
    xpack.security.http.ssl.verification_mode: "${XPACK_SECURITY_HTTP_SSL_VERIFICATION_MODE}"
    xpack.security.http.ssl.key: "${XPACK_SECURITY_HTTP_SSL_KEY}"
    xpack.security.http.ssl.certificate: "${XPACK_SECURITY_HTTP_SSL_CERTIFICATE}"
    xpack.security.http.ssl.certificate_authorities: [ "${XPACK_SECURITY_HTTP_SSL_CERTIFICATE_AUTHORITIES}" ] 
    xpack.security.http.ssl.client_authentication: "${XPACK_SECURITY_HTTP_SSL_CLIENT_AUTHENTICATION}"
    xpack.security.transport.ssl.enabled: "${XPACK_SECURITY_TRANSPORT_SSL_ENABLED}"
    xpack.security.transport.ssl.verification_mode: "${XPACK_SECURITY_TRANSPORT_SSL_VERIFICATION_MODE}"
    xpack.security.transport.ssl.key: "${XPACK_SECURITY_TRANSPORT_SSL_KEY}"
    xpack.security.transport.ssl.certificate: "${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE}" 
    xpack.security.transport.ssl.certificate_authorities: [ "${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE_AUTHORITIES}" ]
    xpack.security.transport.ssl.client_authentication: "${XPACK_SECURITY_TRANSPORT_SSL_CLIENT_AUTHENTICATION}" 
    xpack.security.authc.realms.native.native1.order: 0
    
    # Uncomment this lines in case you need to get debug info related to ES network connections
    # logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
    # logger.org.elasticsearch.discovery: TRACE