---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-elasticsearch-yaml-config
data:
  elasticsearch.yml: |
    cluster.name: "k8s-logs"
    node.name: "${NODE_NAME}"
    network.host: "0.0.0.0"
    discovery.seed_hosts: "${DISCOVERY_SEED_HOSTS}"
    cluster.initial_master_nodes: "${CLUSTER_INITIAL_MASTER_NODES}"
    xpack.license.self_generated.type: "trial"
    xpack.security.enabled: "${XPACK_SECURITY_ENABLED}"
    # Uncomment this lines in case you need to get debug info related to ES network connections
    # logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
    # logger.org.elasticsearch.discovery: TRACE
