apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  template:
    spec:
      containers:
      - name: pingfederate
        resources:
          limits:
            memory: "2Gi"
            cpu: 2
          requests:
            memory: "2Gi"
            cpu: 2
