apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
spec:
  template:
    spec:
      initContainers:
      - name: pingaccess-init
        env:
        - name: WAIT_FOR_SERVICES
          value: pingfederate-admin