apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  nodePools:
    - component: hot
      jvm: -Xms8g -Xmx8g
      replicas: 7 # do not change replicas
      resources:
        requests:
          memory: 8Gi
          cpu: "4"
        limits:
          memory: 10Gi
          cpu: "8"
      roles: # Do not change roles
        - "cluster_manager"
        - "data"
        - "ingest"
        - "remote_cluster_client"
        - "search"