kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

### Lets encrypt ACME certificate issuer for the cluster ###

- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      server: ${LETS_ENCRYPT_SERVER}
      email: ${CLUSTER_NAME_LC}@${DNS_ZONE}
      solvers:
      - dns01:
          route53:
            region: ${REGION}
        selector:
          dnsZones:
          - ${DNS_ZONE}

### Lets encrypt ACME certificate for all endpoints ###
- |-
  apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: acme-tls-cert
    namespace: cert-manager
  spec:
    dnsNames:
    - '*.${DNS_ZONE}'
    keystores:
      pkcs12:
        create: true
        # Password used to encrypt the keystore into which the ACME certs will be added
        passwordSecretRef:
          name: pingcommon-passwords
          key: ACME_CERT_KEYSTORE_PASSWORD

patchesJson6902:

# Change the namespace of the ACME certificate to the ping-cloud namespace
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: acme-tls-cert
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${PING_CLOUD_NAMESPACE}

# PDO-6441: Disable Cert Manager ClusterIssuer preferredChain
# The preferredChain will deploy as an empty string
# This workaround is for the cert-manager defect: https://github.com/cert-manager/cert-manager/pull/6755#issuecomment-1944231410
# Cert manager is still working on a formal fix. Once this is resolved we can revert and will need to upgrade cert-manager
- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt-prod
  patch: |-
    - op: replace
      path: /spec/acme/preferredChain
      value: ""