---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: publish-core-dns-endpoints
  namespace: kube-system
spec:
  jobTemplate:
    metadata:
      labels:
        app: publish-core-dns-endpoints
    spec:
      template:
        metadata:
          labels:
            app: publish-core-dns-endpoints
        spec:
          initContainers:
          - command:
            - /opt/get_core_dns_endpoints.sh
            image: pingidentity/pingfederate:2003-10.0.1
            name: get-core-dns-endpoints
            env:
              - name: TENANT_DOMAIN
                value: surajch.ping-demo.com
            volumeMounts:
            - mountPath: /opt/get_core_dns_endpoints.sh
              name: get-core-dns-endpoints
              subPath: get_core_dns_endpoints.sh
            - mountPath: /config
              name: data-dir
          containers:
          - command: 
            - /bin/python3
            - /opt/put_core_dns_endpoints.py
            image: sthapa7/ping-cloud-aws:0.1
            name: put-core-dns-endpoints
            env:
              - name: TENANT_DOMAIN
                value: surajch.ping-demo.com
              - name: AWS_REGION
                value: us-west-2
            volumeMounts:
            - mountPath: /opt/put_core_dns_endpoints.py
              name: put-core-dns-endpoints
              subPath: put_core_dns_endpoints.py
            - mountPath: /config/core-dns-endpoints
              name: data-dir
              subPath: core-dns-endpoints
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
          volumes:
          - configMap:
              defaultMode: 365
              name: get-core-dns-endpoints
            name: get-core-dns-endpoints
          - configMap:
              defaultMode: 365
              name: put-core-dns-endpoints
            name: put-core-dns-endpoints
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
          volumes:
          - configMap:
              defaultMode: 365
              name: get-core-dns-endpoints
            name: get-core-dns-endpoints
          - configMap:
              defaultMode: 365
              name: put-core-dns-endpoints
            name: put-core-dns-endpoints
          - emptyDir: {}
            name: data-dir
  schedule: 0/15 * * * *

