kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../../base/pingdirectory/aws

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars

patchesStrategicMerge:
- wait-for-service.yaml
- limits.yaml