# Custom patch to kube-state-metrics deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/coreos/kube-state-metrics:v2.9.2
          name: kube-state-metrics
          resources:
            limits:
              cpu: 30m
              memory: 80Mi
            requests:
              cpu: 10m
              memory: 50Mi