# This defines the deployment (as a stateful set) of the pingdirectory servers

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
  namespace: ping-cloud
  labels:
    class: pingdirectory-server
spec:
  serviceName: pingdirectory
  replicas: 2
  selector:
    matchLabels:
      class: pingdirectory-server
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        lastUpdateReason: "NA"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "8080"
        newrelic.io/scrape: "true"
      labels:
        class: pingdirectory-server
        entitled-app: "true"
    spec:
      serviceAccount: ping-serviceaccount
      priorityClassName: high-priority-apps-to-avoid-pending-state
      affinity:
        podAntiAffinity:
          # Add a hard requirement for each PD pod to be deployed to a different node
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - pingdirectory
              topologyKey: "kubernetes.io/hostname"
          # Add a soft requirement for each PD pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - pingdirectory
                topologyKey: "topology.kubernetes.io/zone"
        # this does not apply in dev/test and is removed via kustomize
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pingidentity.com/pd
                    operator: In
                    values:
                      - "true"
      # this does not apply in dev/test and is removed via kustomize
      tolerations:
        - key: "pingidentity.com/pd-only"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 999
      volumes:
      - name: pd-license
        secret:
          secretName: pd-license
      - name: pd-secrets
        secret:
          secretName: pd-secrets
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
      initContainers:
        - name: pd-init
          image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/geoff/pd:10.0.0.2-alpine-example
          imagePullPolicy: Always # Set image pull policy to Always
          command: #["sh", "-c", "sleep 2000"]
            - "./entrypoint.sh"
          env:
            - name: OUT_CONFIG_DIR
              value: "/out/data/config"
            - name: OUT_DB_DIR
              value: "/out/data/db"
            - name: OUT_DIR
              value: "/out/data"
            - name: REGION
              value: "us-west-2"
            - name: RESTART_STRATEGY
              value: "none"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOCAL_INSTANCE_NAME
              value: $(POD_NAME)-$(REGION_NICK_NAME)
            - name: SECRETS_SOURCE_DIR
              value: "/secrets"
            - name: SECRETS_TARGET_DIR
              value: "/sharedSecrets"
          envFrom:
            - configMapRef:
                name: pd-common-config
            - configMapRef:
                name: global-config
          volumeMounts:
            - name: out-dir
              mountPath: /out/data
            - name: pd-license
              mountPath: /opt/pingidentity/license/
            - name: pd-secrets
              mountPath: /secrets
              readOnly: true
      containers:
        - name: pingdirectory
          image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/geoff/pd:10.0.0.2-alpine-example
          imagePullPolicy: Always # Set image pull policy to Always
          resources:
            limits:
              memory: "12Gi"
              cpu: "3"
            requests:
              memory: "12Gi"
              cpu: "2"
          ports:
            - containerPort: 1636 # Expose port 1636
            - containerPort: 8989 # Expose port 8989
          # command: ["sh", "-c", "sleep 2000"]
          envFrom:
            - configMapRef:
                name: pd-common-config
          env:
            - name: REGION
              value: "us-west-2"
            - name: PRIMARY_REGION
              value: "us-west-2"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LDAPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pd-default-config
                  key: LDAPS_PORT
            - name: PD_INIT_SOURCE
              value: "10.0.3.35"
            - name: SECRETS_DIR
              value: /secrets
          volumeMounts:
            - name: out-dir
              mountPath: /opt/pingidentity/runtime/config
              subPath: ./config
            - name: out-dir
              mountPath: /out/data
  volumeClaimTemplates:
    - metadata:
        name: out-dir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: pingdirectory-gp3
        resources:
          requests:
            storage: 50Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: pd-license
  namespace: ping-cloud
data:
  PD.license: SUQ9MDA2NDcxMTAKUHJvZHVjdD1QaW5nRGlyZWN0b3J5ClZlcnNpb249MTAKRW5mb3JjZW1lbnRUeXBlPTMKVGllcj1GcmVlCklzc3VlRGF0ZT0yMDI0LTAzLTI1CkV4cGlyYXRpb25EYXRlPTIwMjUtMDMtMjUKR3JhY2VQZXJpb2Q9MQpEZXBsb3ltZW50TWV0aG9kPURvY2tlcgpPcmdhbml6YXRpb249UGluZyBJZGVudGl0eSBDb3Jwb3JhdGlvbgpTaWduQ29kZT1GRjAzClNpZ25hdHVyZT0zMDJDMDIxNDU0RDExOUQyNDgxQ0FEQ0VDNDBCREMxRjU4QTBEMkIzOEZENzBGMTgwMjE0MkM0QTg3MTVFMjU5OUYyNTc0QUM3MDQzMzBERDBFQzA0ODMxM0VFMA==
---
apiVersion: v1
kind: Secret
metadata:
  name: pd-secrets
  namespace: ping-cloud
type: Opaque
data:
  password.txt: MkZlZGVyYXRlTTByZQo=
  admin-password.txt: MkZlZGVyYXRlTTByZQo=
  encryption-password.txt: MkZlZGVyYXRlTTByZQo=
  ads_cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2akNDQWFZQ0NRQ3NMaEptdEYwQ3VEQU5CZ2txaGtpRzl3MEJBUXNGQURBZ01SNHdIQVlEVlFRRERCVnMKYjJOaGJHaHZjM1F1Ykc5allXeGtiMjFoYVc0d0lCY05NakF3TmpNd01UZ3hOekkwV2hnUE1qRXlNREEyTURZeApPREUzTWpSYU1DQXhIakFjQmdOVkJBTU1GV3h2WTJGc2FHOXpkQzVzYjJOaGJHUnZiV0ZwYmpDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtmalRHZVgweHhubG5LbXBodFB1Z21jRjNXRHREZmsKOUgyWGh4aXpsTzliNzhPWlk3ZGRxZXVpRktBU3ZZZEtzSE80cUVLMXhtMitvTHZaa2RIandFYlc5dVJYQ2Zucgo3cUpRaHpiemZpemtFOXE2MVBHazJTNGNlcytyUlBDZVlFSEUrd1J5bUdnMnNabXgrdVNLb1RvQk5lMnNnQ2lWCkw0YmpBZ3NKdkdxUzI2T0ZleTF6WTVRYXRmUkI0QlFKSis1eFJ3Z3BCSXdJOExRN3ozS0pkQlVyTll3TDlUemYKSVc2UjcxMHlORVhWWkxqa0pwemJTeGtub3kxQlc3SFJwYmxxNFZaWEFEWDNSYlpuV2xKRWhubkRBVGxPcWtregp5cHBUSnhvaEtkK0pZYXRFRUxWNC9DajkyR3UwcEJtSXorazkrWnJob3J1RTBkSHM2T0tlYStVQ0F3RUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVNVcUU1RUw1ZEttNDJWcmFEclpRM0prNXlTUUNtZE1HNGFoYmFndVUKNDk1aEV5NDlhNVhDL3NoS0hCUnJaVy95RTJiS1dTOTBKdzA2aVpUWkk0a3JXZnk5NUtxVlJhWkNYUHc4K0lWdwpLMjJZSTJ1MWVUNlpWYkpuL1dJL2VuMDBwNk1mRjhFTmF3STZTc081dzlVUnRhSFpRK2lhc1BSUERqeVljUC93CnNpbWlBeTB2a2hZSUM5Qmw1K0QxV3FwWm1PRnMvdW5EZC8xUFRxSXF5cHZINUcyYjBvUmdLTTUzQlBIZFBKajAKcEpObFBTblJFNThVNkM5RG5BcSt2cFlJZFE1UWdtQWVaMVA0T2E0cGdHY0NHNlBVYVRoalUxeFhFL01CQWFFRgpwV0pYT2pqWHUwdVpFbXE0bHFJakZEcmZDSkVISkliRmtzMUJjZVVQK3BkU2F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  ads_key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ240MHhubDlNY1o1WnkKcHFZYlQ3b0puQmQxZzdRMzVQUjlsNGNZczVUdlcrL0RtV08zWGFucm9oU2dFcjJIU3JCenVLaEN0Y1p0dnFDNwoyWkhSNDhCRzF2YmtWd241Nis2aVVJYzI4MzRzNUJQYXV0VHhwTmt1SEhyUHEwVHdubUJCeFBzRWNwaG9OckdaCnNmcmtpcUU2QVRYdHJJQW9sUytHNHdJTENieHFrdHVqaFhzdGMyT1VHclgwUWVBVUNTZnVjVWNJS1FTTUNQQzAKTzg5eWlYUVZLeldNQy9VODN5RnVrZTlkTWpSRjFXUzQ1Q2FjMjBzWko2TXRRVnV4MGFXNWF1RldWd0ExOTBXMgpaMXBTUklaNXd3RTVUcXBKTThxYVV5Y2FJU25maVdHclJCQzFlUHdvL2RocnRLUVppTS9wUGZtYTRhSzdoTkhSCjdPamlubXZsQWdNQkFBRUNnZ0VCQUp4NXMwcVNMUWM2WFBTNjhmSmVtb3crV1hjRHE4SzB1Rk1lR2FJaUxsdngKR2tUNkFBQjFZZHZta3NhbThOTGFBQis3S2NnVFY4QU5mZzNYT0p1aFpDSWlWTFo1a1NqSWh2L3RnampyTk54dQpMenNjQzBDMVhsNGwyU2tZL2dZdDlwVVdITWNHYjVvaDcrSEtDb2RiMWUwVUY4bFBqNXREZ0twOWhmZjN1UTZ5CkUxRWl0WHJ6Yk9qNzU4QllXRXc1cXdPS2orWGZIS3FJcDc2dGp6NEM3dlJPUDF5OFBaN1BuYUV2V3VSVXNIdkUKVTB1aXJVc3doYjZJSE10UUxGM21EUEo5Y2lEWmI3NWFjbmtEZTRHc1ZQSHJ5bDNKMGpnZnpNS2dtT1RKZWVFTAprcEsvUHI1eVNMTEZnNjloYVlDU0hLVEt6ME9OUjVXc3dmdjl2WnBjQXNFQ2dZRUEwNEZ3cjcwMitVK3R5d1NNCmlZM0JvNFZEeXVLVXlsQThxUE1COGlCK0cxaXdJenBWSk1hakNZR2dLcUhMZUpGWjM0RGNCUkNiVnZ0RlhpU0UKSW5NQ0taYStlOTh1UXVjcGJzV2tBM3oxT0hMN1dscFp3OTMwZlBkVkNVYW1KZEhYUTJjQ01udDFMRmwyWmVQTwpyVG1rMmdXMHMzYTNHMWRvNjFJM3NZamNHc2tDZ1lFQXl6VFhKa3RUVXZ6L1hqVDhrMDBoUFREWjZzR1RUOEt2CjBERzU0c1ZNYWRTb2hXYi9oUkZ6WHo4Q21YMWQyRDZSS3NaK3pVNjcydCtqY0pDdmd2L3phRWpBZ3M5cXVMTFIKd2s1S29qbmZGT2FobEN3TDladVA0c01kcHZwU2JUS0RPTGdzMXQ1TkcreTlkZEFiSzdMNDFkMTRSbEw4bHZ4OApzdnk4eitvR3VqMENnWUJaU1NGYTd0T1FONVMwU1gxU2JDYzhjbnVGNEZUVGV6L0FTcVdkb3gzWlNYMUJ3ZFJECnJCOFRXa2RVOSt3L1A0empEekRTYW9wSkU5WGF3aXVOcDJOWVR5eW1lamE3UTM1NEpyTHdUZ1h2Q0lzWFAyRDUKa0c4dmVmSEo4cXNjK0JLWmY1aXIydlpCL0pwQXRRU0FsLzhCa3JzUHI2UG94T09qdzVlRE9MVkNFUUtCZ1FDegptNExISURFSDJ3TEQrOFY3Vk9NYU9NR0VFNURuSU1kUkY0S2JnNVBrdnNndEVUcXNIUjZDZ3lrRERhSVM3a3BWCktwa05VcGdML3p0dzFSR3NraHBNaEhGVHJZMUFyeDFqeHR1RXcrMy9oVkl2cXpidTRZNnQrWk9OOFJkRjJTM08KeGtzcnA5VXo1MjRXWWRpQ0tYQnpaNHRWYlNoQk0rM3NMaU9kQ2Ria2FRS0JnUUN4b3ZCYXpjR2VEMXFsRjREUgo0eXZpYUpCeUNPM3ludEQwMXAvUGRCTDJNWHA2bjAzWVZEa1BHUytqamZtamt3QVV0ek9RU2pZUGViWWtlb21yClZMZ2N1YkN1VGZsNmNQbnRxUHZxM1pVT2ZqUlB1REI4MjZ0Rm82RDZEUHYwQ043WnE4Y3ZpK3h0RExqWjRDbG8KdFd3a3JWZ3JTeEljd1dyaTBMcXNXTExmV2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-default-config
  namespace: ping-cloud
data:
  LDAPS_PORT: "1636"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-common-config
  namespace: ping-cloud
data:
  ROOT_USER_PASSWORD_FILE: password.txt
  ADMIN_PASSWORD_FILE: admin-password.txt
  ENCRYPTION_PASSWORD_FILE: encryption-password.txt
  ADS_CERT_FILE: ads_cert.pem
  ADS_KEY_FILE: ads_key.pem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: ping-cloud
data:
  REGION_NICK_NAME: us-west-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-restart-strategy
  namespace: ping-cloud
data:
  RESTART_STRATEGY: ''