kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
- hack-configmaps.yaml
- hack-secrets.yaml
- storage.yaml
- hack-pd.yaml
