apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pingdirectory
spec:
  podSelector:
    matchLabels:
      class: pingdirectory-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Insert secondary region CIDR here
        #- ipBlock:
            #cidr: 172.17.0.0/16
        # Allow PD pods to talk to themselves
        - podSelector:
            matchLabels:
              class: pingdirectory-server
        # For pf-admin we don't want the commonLabels from PD's kustomization.yaml, so we select it a different way
        # https://github.com/kubernetes-sigs/kustomize/issues/2034#issuecomment-618482375
        # We could use `labels:` but then our selectors would change for production customers, potentially causing disruption
        - podSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - pingfederate-admin
      ports:
        # LDAPS
        - protocol: TCP
          port: 1636
        # LDAP
        - protocol: TCP
          port: 1389
        # Replication
        - protocol: TCP
          port: 8989