# This service exposes the pingaccess admin, runtime and agent ports to the
# cluster.

apiVersion: v1
kind: Service
metadata:
  name: pingaccess
spec:
  ports:
  - port: 9000
    name: pa-admin
  - port: 443
    name: pa-runtime
  - port: 3030
    name: pa-agent