kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
- ../cloud-generic
- periodic-backup.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-backup-ops-template-files
  files:
  - backup-ops/backup-ops.sh
  - backup-ops/backup-cm.yaml
  - backup-ops/backup-job.yaml
  - backup-ops/backup-pvc.yaml

patchesStrategicMerge:
- discovery-service.yaml