kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- grafana-dashboards.yaml
<<<<<<< HEAD
configMapGenerator:
- name: grafana-environment-variables
  envs:
  - env_vars
=======
>>>>>>> 38450ae65930067a3b4425152208fad5ee4eb44e
