kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/service-discovery?ref=${K8S_GIT_BRANCH}

# Configure external-dns to only own the hosted zone for the tenant domain
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --domain-filter=${DNS_ZONE}.
  target:
    group: apps
    kind: Deployment
    name: external-dns
    namespace: external-dns
    version: v1
