apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-periodic-csd-upload
data:
  backup-csd-data.sh: |-
    #!/bin/sh

    # Install kubectl
    echo "Installing kubectl"
    curl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
    chmod +x /usr/local/bin/kubectl

    NUM_REPLICAS=$(kubectl get statefulset "${K8S_STATEFUL_SET_NAME}" -o jsonpath='{.spec.replicas}')

    START=0
    END=$((${NUM_REPLICAS} - 1))

    CSD_FILES=
    for i in $(seq ${START} ${END}); do
      SERVER="${K8S_STATEFUL_SET_NAME}-${i}"
      SCRIPT="${HOOKS_DIR}"/82-upload-csd-s3.sh
      LOG_FILE=/tmp/upload.log

      echo "Uploading CSD on server ${SERVER}"
      kubectl exec "${SERVER}" -c "${CSD_CONTAINER_NAME}" -- sh -c "chmod +x ${SCRIPT} && test -x ${SCRIPT} && ${SCRIPT}"> "${LOG_FILE}"

      if test ${?} -eq 0; then
        # Sending logs to STDOUT
        cat ${LOG_FILE}
        CSD_FILE=$(tail -1 "${LOG_FILE}")
        test -z "${CSD_FILES}" && CSD_FILES="${CSD_FILE}" || CSD_FILES="${CSD_FILES} ${CSD_FILE}"
      else
        echo "Upload script not found on server ${SERVER}"
      fi
    done

    # Print the names of the uploaded files so callers know exactly what was uploaded
    echo "The following files were uploaded:"
    echo "${CSD_FILES}"

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingdirectory-periodic-csd-upload
  labels:
    app: ping-cloud
    role: pingdirectory
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingdirectory-periodic-csd-upload
            image: pingidentity/pingdirectory:2006.1-8.1.0.1
            command:
            - /opt/in/backup-csd-data.sh
            env:
            - name: CSD_CONTAINER_NAME
              value: "pingdirectory"
            envFrom:
            - configMapRef:
                name: pingdirectory-environment-variables
            volumeMounts:
            - name: pingdirectory-periodic-csd-upload
              mountPath: /opt/in/backup-csd-data.sh
              subPath: backup-csd-data.sh
          volumes:
          - name: pingdirectory-periodic-csd-upload
            configMap:
              name: pingdirectory-periodic-csd-upload
              defaultMode: 0555