apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
spec:  
  template:
    spec:
      containers:
      - name: pingfederate-admin
        resources:
          limits:
            memory: "2Gi"
            cpu: 2
          requests:
            memory: "2Gi"
            cpu: 2

