## Pipeline stages ##
stages:
- compile
- deploy
- test
- chaos
- cleanup

## Global environment variables ##
variables:
  TENANT_DOMAIN: ci-cd.ping-oasis.com
  DELETE_ENV_AFTER_PIPELINE: 'true'

## Compile stage ##
compile:
  stage: compile
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/compile/compile.sh
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Build stage ##
deploy:
  stage: deploy
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:latest
  script:
  - exit 1 #/ci-scripts/deploy.sh
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
  environment:
    name: $CI_PROJECT_PATH
    on_stop: stop_review
  auto_stop_in: 2 min

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:latest
  script:
  - /ci-scripts/teardown.sh
  when:
    manual
  except:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
  environment:
    name: $CI_PROJECT_PATH
    action: stop

## Test stage ##
pd-tests:
  stage: test
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh pingdirectory
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

pf-tests:
  stage: test
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh pingfederate
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

pa-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh pingaccess
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

integration-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh integration
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Chaos testing stage ##
chaos-tests:
  stage: chaos
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh chaos
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Cleanup stage ##
cleanup:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:latest
  script:
  - /ci-scripts/teardown.sh
  except:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
  environment:
    name: $CI_PROJECT_PATH
    action: stop