workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    # Handle Tag Pipelines (Ensures releases/tags trigger the pipeline)
    - if: $CI_COMMIT_TAG
    # If an MR is open, run a "Merge Request Pipeline"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Scheduled pipelines
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # If a branch is pushed but HAS an open MR, don't run a redundant branch pipeline
    # - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
    #   when: never
    # Otherwise, run for standard branch pushes
    - if: $CI_COMMIT_BRANCH

## Pipeline stages ##
stages:
- compile
- find-cluster
- deploy
- pre-check-test
- pa-was-test
- integration-test
- chaos
- cleanup
- merge-branch
- security # move this to the end and we'll use the "needs" keyword to allow it to run earlier and out of order

## Global environment variables ##
variables:
  AUTO_MERGE: $AUTO_MERGE
  DELETE_ENV_AFTER_PIPELINE: 'true'
  CLUSTER_POSTFIXES: '_9 _10 _11 _12'
  K8S_DEPLOY_TOOLS: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:v2.3-release-branch
  SHARED_CI_SCRIPTS_DIR: "/ci-scripts"
  # 01-test-ocsp-stapling.sh causes other failures due to NGINX restart - ticket to fix is PDO-8100
  BRANCH_SKIP_TESTS: >
    pingaccess/08-artifact-test.sh
    pingdelegator/01-admin-user-login.sh
    ingress-nginx/01-test-ocsp-stapling.sh

## Compile stage ##
compile:
 stage: compile
 tags:
   - default-gitlab-runner-ping-cloud
 image: ${K8S_DEPLOY_TOOLS}
 script:
   - |
     ${SHARED_CI_SCRIPTS_DIR}/k8s/compile/compile.sh

## start security stage ##
copy-images:
  stage: security
  image: ${K8S_DEPLOY_TOOLS}
  needs:
    - deploy
  dependencies:
    - deploy
  variables:
    BELUGA_VERSION: $CI_COMMIT_REF_NAME
    ARTIFACTORY_URL: "docker.corp.pingidentity.com:5900"
    ARTIFACTORY_PATH: "beluga-xray"
    UBER_YAML: $CI_PROJECT_DIR/out/_builds_ping-cloud-private-tenant_ping-cloud-base.yaml
  allow_failure: true
  before_script:
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | HOME=/tmp docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/security/copy-images.sh
  tags:
    - platform-publish-docker
  only:
    - /^.*-release-branch$/

check-ext-images:
  stage: security
  image: ${K8S_DEPLOY_TOOLS}
  needs:
    - deploy
  dependencies:
    - deploy
  variables:
    UBER_YAML: $CI_PROJECT_DIR/out/_builds_ping-cloud-private-tenant_ping-cloud-base.yaml
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/security/check_ext_images.sh $UBER_YAML
  tags:
    - default-gitlab-runner-ping-cloud

scan:
  stage: security
  image: ${K8S_DEPLOY_TOOLS}
  needs:
    - deploy
  dependencies:
    - deploy
  variables:
    GIT_STRATEGY: none
    UBER_YAML: $CI_PROJECT_DIR/out/_builds_ping-cloud-private-tenant_ping-cloud-base.yaml
  allow_failure: true
  script:
    - kubescape scan --format json --format-version v2 --verbose --output report.json framework all $UBER_YAML
  tags:
    - platform-publish-docker
  artifacts:
    paths:
    - report.json
    expire_in: 1 year
  only:
    - /^.*-release-branch$/
## end security stage ##

## Find cluster stage ##
find-cluster:
  stage: find-cluster
  # Run in parallel with compile stage
  needs: []
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/deploy/find_cluster.sh
  artifacts:
    reports:
      dotenv: cluster.env

## Deploy stage ##
deploy:
  stage: deploy
  needs:
    - find-cluster
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  variables:
    YAML_OUT_DIR: $CI_PROJECT_DIR/out
  before_script:
    - mkdir -p $YAML_OUT_DIR
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/deploy/deploy.sh
  artifacts:
    paths:
      - out/
  dependencies:
    - find-cluster

## Integration Test stage ##

# Common pre-check tests
pre-check:
  stage: pre-check-test
  retry: 1
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh pre-check
  dependencies:
    - find-cluster

## PA-WAS stage ##
pa-was-integration-tests:
  stage: pa-was-test
  retry: 1
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh pingaccess-was
  dependencies:
    - find-cluster
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "k8s-configs/ping-cloud/base/pingaccess-was/**/*"
        - "code-gen/templates/common/base/ping-cloud/pingaccess-was/**/*"
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

################################################
# All integration tests defined to run on the  #
# traditionally deployed P1AS                  #
################################################
.all-tests: &all-tests
  - pingdirectory
  - pingdelegator
  - pingfederate
  - pingaccess
  - pingcloud-services
  - pingcentral
  - pingdatasync
  - common
  - monitoring
  - health
  - pingone
  - ingress-nginx
  - cert-manager
  - logging
  - self-service
  - argocd
  - system-scaling

################################################
# All integration tests defined to run on the  #
# traditionally deployed P1AS                  #
################################################
.chub-tests: &chub-tests
  - pingcloud-services
  - pingcentral
  - common
  - monitoring
  - health

.integration-tests-base:
  variables:
    TEST: ""
    UBER_YAML: $CI_PROJECT_DIR/out/_builds_ping-cloud-private-tenant_ping-cloud-base.yaml
  stage: integration-test
  retry: 1
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - export SKIP_TESTS="${BRANCH_SKIP_TESTS}"
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh ${TEST}
  dependencies:
    - find-cluster
    - compile
  artifacts:
    name: "integration_test_logs"
    paths:
      - tests/pingone/latest_logs/
    when: on_failure

integration-tests:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *all-tests
  rules:
    # DO NOT run this full suite on Merge Requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: never
    - if: '$ENV_TYPE == null && $CI_PIPELINE_SOURCE != "schedule"'
    # Do not run on nightly builds
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never

.manual-web-rule: &manual-web-rule
  - if: '$CI_PIPELINE_SOURCE == "web"'
    when: manual
    allow_failure: true

.mr-rules-map:
  argocd: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "k8s-configs/ping-cloud/base/argocd/**/*"
        - "code-gen/templates/common/base/argocd/**/*"
    - *manual-web-rule
  cert-manager: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/common/base/cluster-tools/cert-manager/**/*"
    - *manual-web-rule
  common: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/common/base/ping-cloud/**/*"
    - *manual-web-rule
  health: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/cluster-tools/base/health/**/*"
    - *manual-web-rule
  cluster-tools: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/p1as-cluster-tools/**/*"
    - *manual-web-rule
  logging: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/cluster-tools/base/logging/**/*"
        - "code-gen/templates/common/base/cluster-tools/logging/**/*"
    - *manual-web-rule
  monitoring: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/cluster-tools/base/monitoring/**/*"
        - "code-gen/templates/common/base/cluster-tools/monitoring/**/*"
    - *manual-web-rule
  pingaccess: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/ping-cloud/base/pingaccess/**/*"
        - "k8s-configs/ping-cloud/prod/large/pingaccess/**/*"
        - "k8s-configs/ping-cloud/prod/medium/pingaccess/**/*"
        - "k8s-configs/ping-cloud/prod/small/pingaccess/**/*"
        - "k8s-configs/ping-cloud/prod/x-small/pingaccess/**/*"
        - "code-gen/templates/common/base/ping-cloud/pingaccess/**/*"
        - "k8s-configs/ping-cloud/base/pingaccess/**/*"
        - "code-gen/templates/p1as-pingaccess/**/*"
    - *manual-web-rule
  pingcentral: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/ping-cloud/base/pingcentral/**/*"
        - "k8s-configs/ping-cloud/prod/large/pingcentral/**/*"
        - "k8s-configs/ping-cloud/prod/medium/pingcentral/**/*"
        - "k8s-configs/ping-cloud/prod/small/pingcentral/**/*"
        - "k8s-configs/ping-cloud/prod/x-small/pingcentral/**/*"
        - "k8s-configs/ping-cloud/base/pingcentral/**/*"
    - *manual-web-rule
  pingcloud-services: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/ping-cloud/base/pingcloud-services/**/*"
    - *manual-web-rule
  pingdatasync: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "k8s-configs/ping-cloud/base/pingdatasync/**/*"
        - "k8s-configs/ping-cloud/prod/large/pingdatasync/**/*"
        - "k8s-configs/ping-cloud/prod/medium/pingdatasync/**/*"
        - "k8s-configs/ping-cloud/prod/small/pingdatasync/**/*"
        - "k8s-configs/ping-cloud/prod/x-small/pingdatasync/**/*"
        - "k8s-configs/ping-cloud/base/pingdatasync/**/*"
    - *manual-web-rule
  pingdelegator: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "k8s-configs/ping-cloud/base/pingdelegator/**/*"
        - "k8s-configs/ping-cloud/prod/large/pingdelegator/**/*"
        - "k8s-configs/ping-cloud/prod/medium/pingdelegator/**/*"
        - "k8s-configs/ping-cloud/prod/small/pingdelegator/**/*"
        - "k8s-configs/ping-cloud/prod/x-small/pingdelegator/**/*"
        - "code-gen/templates/cde/base/ping-cloud/pingdelegator/**/*"
    - *manual-web-rule
  pingdirectory: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/p1as-pingdirectory/**/*"
    - *manual-web-rule
  pingfederate: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/p1as-pingfederate/**/*"
    - *manual-web-rule
  pingone: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "k8s-configs/ping-cloud/base/pingone/**/*"
    - *manual-web-rule
  self-service: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: 
        - "code-gen/templates/p1as-self-service/**/*"
    - *manual-web-rule

# Nightly Build Tests
nightly-build-tests:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *all-tests
  rules:
    - if: '$ENV_TYPE != "customer-hub" && $CI_PIPELINE_SOURCE == "schedule"'

integration-tests-chub:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *chub-tests
  rules:
  - if: '$ENV_TYPE == "customer-hub"'

# Argocd integration test
argocd:
  extends: .integration-tests-base
  variables:
    TEST: argocd
  rules: !reference [.mr-rules-map, argocd]

# cert-manager integration test
cert-manager:
  extends: .integration-tests-base
  variables:
    TEST: cert-manager
  rules: !reference [.mr-rules-map, cert-manager]

# common integration test
common:
  extends: .integration-tests-base
  variables:
    TEST: common
  rules: !reference [.mr-rules-map, common]

# Health integration test
health:
  extends: .integration-tests-base
  variables:
    TEST: health
  rules: !reference [.mr-rules-map, health]

# cluster-tools integration Test
cluster-tools:
  extends: .integration-tests-base
  parallel:
    matrix:
      - TEST:
        - ingress-nginx
        - system-scaling
  rules: !reference [.mr-rules-map, cluster-tools]

# logging integration test
logging:
  extends: .integration-tests-base
  variables:
    TEST: logging
  rules: !reference [.mr-rules-map, logging]

# monitoring integration test
monitoring:
  extends: .integration-tests-base
  variables:
    TEST: monitoring
  rules: !reference [.mr-rules-map, monitoring]

# PingAccess integration Test
pingaccess:
  extends: .integration-tests-base
  variables:
    TEST: pingaccess
  rules: !reference [.mr-rules-map, pingaccess]

# PingCentral integration Test
pingcentral:
  extends: .integration-tests-base
  variables:
    TEST: pingcentral
  rules: !reference [.mr-rules-map, pingcentral]

# PingCloud Services integration Test
pingcloud-services:
  extends: .integration-tests-base
  variables:
    TEST: pingcloud-services
  rules: !reference [.mr-rules-map, pingcloud-services]

# PingDataSync integration Test
pingdatasync:
  extends: .integration-tests-base
  variables:
    TEST: pingdatasync
  rules: !reference [.mr-rules-map, pingdatasync]

# PingDelegator integration test
pingdelegator:
  extends: .integration-tests-base
  variables:
    TEST: pingdelegator
  rules: !reference [.mr-rules-map, pingdelegator]

# PingDirectory integration Test
pingdirectory:
  extends: .integration-tests-base
  variables:
    TEST: pingdirectory
  rules: !reference [.mr-rules-map, pingdirectory]

# PingFederate integration Test
pingfederate:
  extends: .integration-tests-base
  variables:
    TEST: pingfederate
  rules: !reference [.mr-rules-map, pingfederate]

# PingOne integration Test
pingone:
  extends: .integration-tests-base
  variables:
    TEST: pingone
  rules: !reference [.mr-rules-map, pingone]

# self-service integration test
self-service:
  extends: .integration-tests-base
  variables:
    TEST: self-service
  rules: !reference [.mr-rules-map, self-service]

## Chaos testing stage ##
chaos-tests:
  stage: chaos
  retry: 1
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh chaos
  dependencies:
    - find-cluster
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

.cleanup-base:
  stage: cleanup
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/cleanup/teardown.sh

## Cleanup stage that runs when everything has succeeded ##
cleanup-on-success:
  extends: .cleanup-base
  dependencies:
    - find-cluster

## Cleanup stage for failed compile stage ##
cleanup-on-compile-failure:
  extends: .cleanup-base
  needs:
    - compile
    - find-cluster
    - deploy
  when: on_failure
  script:
    # Only cleanup when compile fails.
    # If compile passes, deployment remains for troubleshooting
    - |
      if [ "$COMPILE_RESULT" != 0 ]; then
        ${SHARED_CI_SCRIPTS_DIR}/k8s/cleanup/teardown.sh;
      else
        echo "Compile passed, deployment not torn down to allow for troubleshooting";
      fi

merge-branch:   # Merge current release branch to next upstream release branch
  stage: merge-branch
  tags:
    - default-gitlab-runner-ping-cloud
  image: ${K8S_DEPLOY_TOOLS}
  needs:
    - cleanup-on-success
  script:
    - source ${SHARED_CI_SCRIPTS_DIR}/release/merge-branch.sh
    - merge_release_branch
  variables:
    CREATE_MR: "yes"
  rules:
    - if: '$AUTO_MERGE == "true" && $CI_COMMIT_BRANCH =~ /^v*.*-release-branch$/'
