apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: performing-pingdirectory-restore-
spec:
  ttlStrategy:
    secondsAfterSuccess: 30
  serviceAccountName: ping-serviceaccount
  entrypoint: main # What first task/template you will run
  templates:
    - name: main
      steps:
        - - name: get-pods
            templateRef:
              name: pingdirectory-restore
              template: get-pods

          - name: set-argo-workflow-configmap-to-restore
            templateRef:
              name: pingdirectory-restore
              template: set-argo-workflow-configmap
            arguments:
              parameters:
                - name: argo_workflow_type
                  value: "RESTORE"

        - - name: cleanup
            templateRef:
              name: pingdirectory-restore
              template: cleanup-pingdirectory-workspace
              dependencies: [ set-argo-workflow-configmap-to-restore ]
            arguments:
              parameters:
                - name: pingdirectory_pod_name
                  value: "{{item}}"
            withParam: "{{steps.get-pods.outputs.parameters.pods-list}}"

        - - name: restoring-pingdirectory
            templateRef:
              name: pingdirectory-restore
              template: wait-for-all-pods-to-start
            arguments:
              parameters:
                - name: pingdirectory_pod_name
                  value: "pingdirectory-0"

        - - name: verify-pingdirectory-0-server-status-after-restore
            templateRef:
              name: pingdirectory-restore
              template: run-kubectl
            arguments:
              parameters:
                - name: server
                  value: "pingdirectory-0"
                - name: cmd
                  value: "status"

        - - name: wait-for-the-other-pingdirectory-servers-to-start
            templateRef:
              name: pingdirectory-restore
              template: wait-for-all-pods-to-start
            arguments:
              parameters:
                - name: pingdirectory_pod_name
                  value: "{{item}}"
            withParam: "{{steps.get-pods.outputs.parameters.pods-list}}"

        - - name: dsreplication-status
            templateRef:
              name: pingdirectory-restore
              template: run-kubectl
            arguments:
              parameters:
                - name: server
                  value: "{{item}}"
                - name: cmd
                  value: "dsreplication status"
            withParam: "{{steps.get-pods.outputs.parameters.pods-list}}"

        - - name: reset-argo-workflow-configmap
            templateRef:
              name: pingdirectory-restore
              template: set-argo-workflow-configmap
            arguments:
              parameters:
                - name: argo_workflow_type
                  value: ""