kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- k8s-configs

patchesStrategicMerge:

# DEVOPS user/key
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingaccess-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
    PA_ADMIN_PUBLIC_HOSTNAME: pingaccess-admin.${TENANT_DOMAIN}
    PA_ENGINE_PUBLIC_HOSTNAME: pingaccess.${TENANT_DOMAIN}
    PF_ADMIN_PUBLIC_HOSTNAME: pingfederate-admin.${TENANT_DOMAIN}
    PF_ENGINE_PUBLIC_HOSTNAME: pingfederate.${TENANT_DOMAIN}
    BACKUP_URL: ${BACKUP_URL}
    REGION: ${REGION}
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingdirectory-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
    PA_ADMIN_PUBLIC_HOSTNAME: pingaccess-admin.${TENANT_DOMAIN}
    PA_ENGINE_PUBLIC_HOSTNAME: pingaccess.${TENANT_DOMAIN}
    PF_ADMIN_PUBLIC_HOSTNAME: pingfederate-admin.${TENANT_DOMAIN}
    PF_ENGINE_PUBLIC_HOSTNAME: pingfederate.${TENANT_DOMAIN}
    REGION: ${REGION}
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingfederate-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
    PA_ADMIN_PUBLIC_HOSTNAME: pingaccess-admin.${TENANT_DOMAIN}
    PA_ENGINE_PUBLIC_HOSTNAME: pingaccess.${TENANT_DOMAIN}
    PF_ADMIN_PUBLIC_HOSTNAME: pingfederate-admin.${TENANT_DOMAIN}
    PF_ENGINE_PUBLIC_HOSTNAME: pingfederate.${TENANT_DOMAIN}
    BACKUP_URL: ${BACKUP_URL}
    REGION: ${REGION}

patchesJson6902:

# Ingress
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingdataconsole-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdataconsole.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingdataconsole.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: kibana-ingress
    namespace: elastic-stack-logging
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: logs.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: logs.${TENANT_DOMAIN}

### Monitoring dashboard ###
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: grafana-ingress
    namespace: prometheus
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: monitoring${DNS_RECORD_SUFFIX}.${DNS_DOMAIN_PREFIX}${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: monitoring${DNS_RECORD_SUFFIX}.${DNS_DOMAIN_PREFIX}${TENANT_DOMAIN}

### Prometheus Endpoint ###
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: prometheus-ingress
    namespace: prometheus
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: prometheus${DNS_RECORD_SUFFIX}.${DNS_DOMAIN_PREFIX}${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: prometheus${DNS_RECORD_SUFFIX}.${DNS_DOMAIN_PREFIX}${TENANT_DOMAIN}

# pingdirectory put ldaps on public and change the host
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        external-dns.alpha.kubernetes.io/hostname: pingdirectory-admin.${TENANT_DOMAIN}

# Make the admin nodes available externally for test purposes. In general, they
# will be behind a VPN gateway on all CDEs so only admins have access to them.
- target:
    version: v1
    kind: Service
    name: ingress-nginx
    namespace: ingress-nginx-private
  patch: |-
    - op: replace
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb

# Configure external-dns to only own the hosted zone for the tenant domain
- target:
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
    namespace: external-dns
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --domain-filter=${TENANT_DOMAIN}.