kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- k8s-configs

# DEVOPS user/key
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingaccess-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingdirectory-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingfederate-environment-variables
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY}

# Ingress
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingdataconsole-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdataconsole.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingdataconsole.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: kibana-ingress
    namespace: elastic-stack-logging
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: logs.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: logs.${TENANT_DOMAIN}

- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: chronograf-ingress
    namespace: chronograf
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: monitoring.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: monitoring.${TENANT_DOMAIN}

# pingdirectory put ldaps on public and change the host
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        external-dns.alpha.kubernetes.io/hostname: pingdirectory-admin.${TENANT_DOMAIN}

# Make the admin nodes available externally for test purposes. In general, they
# will be behind a VPN gateway on all CDEs so only admins have access to them.
- target:
    version: v1
    kind: Service
    name: ingress-nginx
    namespace: ingress-nginx-private
  patch: |-
    - op: replace
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb