kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1


resources:
  # Apply PingAccess admin deployment resources
  - ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess/admin?ref=${K8S_GIT_BRANCH}

images:
  - name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess${ECR_ENV}
    newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess${ECR_ENV}
    newTag: ${PINGACCESS_IMAGE_TAG}

patches:
  ### PingAccess Admin Last Update Config Map ###
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: pingaccess-admin-last-update-config
    target:
      group: apps
      kind: StatefulSet
      name: pingaccess-admin
      version: v1
  ### Ingress patches ###
  - patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pingaccess-admin-api.${DNS_ZONE}
      - op: replace
        path: /spec/rules/0/host
        value: pingaccess-admin-api.${DNS_ZONE}
    target:
      group: networking.k8s.io
      kind: Ingress
      name: pingaccess-admin-ingress
      version: v1
  # pingaccess admin api
  # Set a hostname for all the headless services so their endpoint IPs are published to Route53
  - patch: |-
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: pingaccess-cluster.${DNS_ZONE}
    target:
      kind: Service
      name: pingaccess-admin
      version: v1
