kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: kube-system

resources:
- github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.5.8

patchesStrategicMerge:
  - |-
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: efs-csi-controller
    spec:
      template:
        spec:
          containers:
          - name: efs-plugin
            args:
              - --endpoint=$(CSI_ENDPOINT)
              - --logtostderr
              - --v=2
              - --delete-access-point-root-dir=true
              - --vol-metrics-opt-in=false
            resources:
              limits:
                memory: "300Mi"
                cpu: "40m"
              requests:
                memory: "200Mi"
                cpu: "20m"
          - name: csi-driver-registrar
            resources:
              limits:
                memory: "50Mi"
                cpu: "20m"
              requests:
                memory: "30Mi"
                cpu: "10m"
          - name: liveness-probe
            resources:
              limits:
                memory: "50Mi"
                cpu: "20m"
              requests:
                memory: "30Mi"
                cpu: "10m"
