apiVersion: batch/v1
kind: Job
metadata:
  name: p14c-oauth-service
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  # 24-hour TTL for debugging
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      serviceAccountName: p14c-oauth-serviceaccount
      containers:
      - name: pingcloud-oauth
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration/dev:v1.19-release-branch-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: p14c-oauth-service-environment-variables
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        # The -u flag is necessary for python to emit logging to standard out
        command: [ 'python3', '-u', '/app/oauth_client_services_controller.py' ]
      restartPolicy: Never
