kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # TODO: add back but without CRDs???? ugh
  - base
  - pf-provisioning

patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: postgresclusters.postgres-operator.crunchydata.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: pgupgrades.postgres-operator.crunchydata.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"