apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "6"
              memory: 9Gi
            requests:
              cpu: "6"
              memory: 9Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms8000m -Xmx8000m'
            - name: PIPELINE_WORKERS
              value: "10"
            - name: QUEUE_MAX_BYTES
              value: 2000gb
            - name: PIPELINE_BATCH_SIZE
              value: '5000'
