kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
data:
  use-proxy-protocol: "true"
  real-ip-header: "proxy_protocol"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services