kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
data:
  main-snippet: load_module /usr/lib/nginx/modules/ngx_http_sigsci_nxo_module-1.17.7.so;
  http-snippet: sigsci_agent_host unix:/sigsci/tmp/sigsci.sock;

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services