apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms1500m -Xmx1500m'
            - name: PIPELINE_WORKERS
              value: "2"
            - name: QUEUE_MAX_BYTES
              value: 1000gb
            - name: PIPELINE_BATCH_SIZE
              value: '1000'
