# Admin user created in the security-config. Here it's used to authorize OS operator to the OS
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-config
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  username: YWRtaW4=
  password: b3dVbmZVUG9HeFBUNVd2

---
# OS Dashboards usercreated in the security-config
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-dashboards-admin-config
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  username: ZGFzaGJvYXJkcw==
  password: TFpTWmN4OG9yUkhXbmc2