---

# In order to change the PingCentral admin password, 2 rollouts are necessary.
#
# 1. On the 1st rollout, change the PC_ADMIN_USER_PASSWORD as appropriate and the
#    LAST_UPDATE_REASON for PingCentral. This will cause a rollout/restart of
#    the PingCentral pod.
# 2. On the 2nd rollout, change the OLD_PC_ADMIN_USER_PASSWORD to match the
#.   PC_ADMIN_USER_PASSWORD. This will cause an update of the secret.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords

---

### Licenses ###

# Add pingcentral.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingcentral-license
type: Opaque

---