apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public
spec:
  template:
    spec:
      containers:
      - name: sigsci-agent
        $patch: delete