kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- ../../../base/logging/

patches:
- path: elastic-stack/logstash/logstash-limits.yaml
- path: elastic-stack/logstash/hpa-limits.yaml
