kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Apply PingCentral deployment resources
resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcentral/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingcentral${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingcentral${ECR_ENV}
  newTag: ${PINGCENTRAL_IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingcentral-last-update-config
  target:
    group: apps
    kind: Deployment
    name: pingcentral
    version: v1
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingcentral.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingcentral.${DNS_ZONE}
  target:
    group: networking.k8s.io
    kind: Ingress
    name: pingcentral-ingress
    version: v1
