---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: publish-core-dns-endpoints
  namespace: kube-system
spec:
  schedule: 0/6 * * * *
  jobTemplate:
    metadata:
      labels:
        app: publish-core-dns-endpoints
    spec:
      template:
        metadata:
          labels:
            app: publish-core-dns-endpoints
        spec:
          containers:
          - name: publish-core-dns-endpoints
            command:
            - /bin/python3
            - /opt/publish_endpoints.py
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/mpeterson/ping-cloud-tools:latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: core-dns-environment-variables
            volumeMounts:
            - mountPath: /opt/publish_endpoints.py
              name: publish-core-dns-endpoints
              subPath: publish_endpoints.py
            - mountPath: /opt/common/
              name: common
            - mountPath: /opt/templates/
              name: kustomize-templates
            - mountPath: /opt/templates/patch/base/
              name: kustomize-templates-patch-base
            - mountPath: /opt/templates/patch/overlay/
              name: kustomize-templates-patch-overlay
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
          volumes:
          - name: publish-core-dns-endpoints
            configMap:
              defaultMode: 365
              name: publish-core-dns-endpoints
          - name: common
            configMap:
              defaultMode: 365
              name: common
          - name: kustomize-templates
            configMap:
              defaultMode: 365
              name: kustomize-templates
          - name: kustomize-templates-patch-base
            configMap:
              defaultMode: 365
              name: kustomize-templates-patch-base
          - name: kustomize-templates-patch-overlay
            configMap:
              defaultMode: 365
              name: kustomize-templates-patch-overlay
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
