kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- rbac.yaml
- cronjobs.yaml

namespace: kube-system

configMapGenerator:
- name: publish-core-dns-endpoints
  files:
  - src/publish_endpoints.py

- name: core-dns-environment-variables
  envs:
    - env_vars

- name: core-dns-templates
  files:
  - src/core-dns-templates.zip

# We should be able to remove hostname-ip
- name: hostname-ip
  files:
  - src/hostname-ip.txt
generatorOptions:
  disableNameSuffixHash: true
