apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was
        resources:
          requests:
            memory: 2560Mi
            cpu: 2
          limits:
            memory: 3Gi
            cpu: 2

  replicas: 2