apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  template:
    spec:
      initContainers:
      - name: pingfederate-init
        env:
        # PF engines must wait until the PF admin is ready
        # A space-separated list of deployments or statefulsets that this app should wait for
        - name: WAIT_FOR_SERVICES
          value: pingfederate-admin