apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator-upgrade
$patch: delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator
$patch: delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator-upgrade
$patch: delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator
$patch: delete

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator-upgrade
$patch: delete

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgo
$patch: delete