apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${REGION_NICK_NAME}"
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-configs/${REGION_NICK_NAME}
    repoURL: ${CLUSTER_STATE_REPO_URL}
    targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
    plugin:
      name: git-ops-command