apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingfederate
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingfederate
  targetCPUUtilizationPercentage: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        type: Pods
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        type: Pods
        value: 1
periodSeconds: 5
