apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  template:
    spec:
      containers:
      - name: stunnel
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
