pingdirectory:  
  serverProfilePath: "profiles/pingdirectory"
  backupFileName: ""
  # This is the environment variable to select the backend(s) to restore in PD
  # Allowed values:appintegrations platformconfig userRoot userRoot_2 userRoot_3 userRoot_4 userRoot_5
  # Seperated with a semi-colon(;) Example: userRoot;userRoot_2
  # No values set would just restore all backends in PD
  backendsToRestore: ""
  # Define the contents for your descriptor.json file here, in yaml. An example is provided below for syntax.
  # descriptorFile: |-
  #   us-west-2:
  #     hostname: abc
  #     replicas: 1
  #   us-east-2:
  #     hostname: def
  #     replicas: 2
  descriptorFile: ""
  monitorBucketUrl: "ssm://cluster-name/pcpt/service/storage/pd-monitor/uri"
  # Changes PURGE_BATCH_SIZE for -Dcom.unboundid.directory.server.plugins.PurgeExpiredDataPlugin.BATCH_SIZE= - default is 10000
  purgeBatchSize: "10000"
  # Add auth cert(s) - space delimited if multiple - here to enable X.509-based authentication via SASL
  # More info here: https://confluence.pingidentity.com/display/proserv/Enabling+X.509+Authentication+with+PingDirectory
  # Example: PD_X509_AUTH_CERTS=cert_one cert_two
  pdX509AuthCerts: ""
  # Set to false to avoid skipping liveness probe. Skipping the liveness (SKIP_LIVENESS=true) is the default for PingDirectory.
  skipLiveness: true
  # Customization for pingdirectory ingress resource
  ingress:
    enableExternalIngress: false
    # Customization for pingdirectory service resource
    ingressClassName: "nginx-private"
  statefulSet:
    lastUpdateReason: "NA"
    replicas: "3"
    # Set container limits for the pingdirectory deployment
    resources:
      limits:
        memory: "4Gi"
        cpu:  "2"
      requests:
        memory: "4Gi"
        cpu: "2"
  # Persistent volume size configuration.
  persistentVolume:
    size: 40Gi
    # Storage class Name configuration for the persistent volume.
    storageClassName: "pingdirectory-gp3"
    # Storage provisioner configuration for managing the persistent volume.
    storageProvisioner: "ebs.csi.aws.com"
    # File system type configuration for the persistent volume.
    fsType: "ext4"
    # Storage type configuration for the persistent volume.
    storageType: "gp3"
  # PingDirectory Shared Cache Settings 
  # Set this to 'true' to use shared cache for the local backends
  pdUseSharedCache: "false"
  # Set this to define overall cache size .This would to be shared across all local backends
  sharedCachePercent: "55"