kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../base/kube-downscaler

# Patch kube-downscaler to zero replicas
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kube-downscaler
      namespace: default
    spec:
      replicas: 0
