### This is originally an exact copy of secrets.yaml and left around for future reference. It does NOT contain any
### secrets and safe to leave around.

### Product passwords ###

# Supported keys:
# Exported as environment variables: PF_ADMIN_USER_PASSWORD, PF_LDAP_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords

---

# Supported keys:
# Mounted as files: root-user-password, admin-user-password, encryption-password, encryption-settings.pin
# Exported as environment variables: P14C_ENVIRONMENT_ID, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdirectory-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
#                                    P14C_ISSUER, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    ${SSH_ID_KEY_BASE64}

---
