kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Apply PingFederate admin deployment resources
resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingfederate/admin?ref=${K8S_GIT_BRANCH}



images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingfederate${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingfederate${ECR_ENV}
  newTag: ${PINGFEDERATE_IMAGE_TAG}
- name: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-integration${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-integration${ECR_ENV}
  newTag: ${P14C_INTEGRATION_IMAGE_TAG}

patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingfederate-admin-last-update-config
  target:
    group: apps
    kind: StatefulSet
    name: pingfederate-admin
    version: v1
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin-api.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin-api.${DNS_ZONE}
  target:
    group: networking.k8s.io
    kind: Ingress
    name: pingfederate-admin-ingress
    version: v1
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster.${DNS_ZONE}
  target:
    kind: Service
    name: pingfederate-cluster
    version: v1
