apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectoryproxy-environment-variables
data:
  ORCHESTRATION_TYPE: "kubernetes"
  VERBOSE: "false"
  SERVER_PROFILE_PATH: "pingdirectoryproxy"
  SERVER_PROFILE_URL: "https://github.com/calvincarter-ping/hackathon-profiles.git"
  SERVER_PROFILE_BRANCH: "v1.19-release-branch"
  REGION: "us-west-2"
  LOCATION: "austin"
  K8S_STATEFUL_SET_NAME: "pingdirectoryproxy"
  K8S_STATEFUL_SET_SERVICE_NAME: "pingdirectoryproxy"
  PING_IDENTITY_ACCEPT_EULA: "YES"
  P1AS_PDP_LDAP_PORT: "1389"
  P1AS_PDP_LDAPS_PORT: "1636"
  P1AS_PDP_HTTPS_PORT: "1443"
  TAIL_LOG_FILES: ""
  SERVER_ROOT_DIR: "/opt/out/instance"
  K8S_TAIL_LOG_FILES: "/opt/out/instance/logs/access /opt/out/instance/logs/errors /opt/out/instance/logs/failed-ops /opt/out/instance/logs/tools/.log /opt/server/logs/tools/.log"
  ROOT_BIND_DN: "cn=administrator"
  SECRETS_DIR: "/usr/local/secrets"
  ROOT_USER_PASSWORD_FILE: "/usr/local/secrets/root-user-password"
  P1AS_PD_SERVER: "p1as_pd_server"
  P1AS_PD_POD_NAME: "pingdirectory-0"
  P1AS_PD_PRIVATE_HOSTNAME: "pingdirectory"
  CUSTOMER_SSM_PATH_PREFIX: "/calvincarter-secondary/pcpt/customer"
  CUSTOMER_SSO_SSM_PATH_PREFIX: "/calvincarter-secondary/pcpt/customer/sso"
  IS_BELUGA_ENV: "true"
  IS_MULTI_CLUSTER: "false"
  TOPOLOGY_DESCRIPTOR_JSON: "/opt/staging/topology/descriptor.json"
  TOPOLOGY_DESCRIPTOR_PROFILES_JSON: "/opt/staging/topology/descriptor-profiles.json"
  USER_BACKEND_ID: "userRoot"
  USER_BASE_DN: "dc=example,dc=com"
  PING_IDENTITY_DEVOPS_KEY: "ssm://pcpt/devops-license/key"
  PING_IDENTITY_DEVOPS_USER: "ssm://pcpt/devops-license/user"