apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: p1as-pingdirectoryproxy-role
rules:
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
      - "secrets"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
    verbs:
      - delete
      - get
      - create
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "statefulsets"
      - "deployments"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingdirectoryproxy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: p1as-pingdirectoryproxy-role
subjects:
  - kind: ServiceAccount
    name: pingdirectoryproxy-serviceaccount