# Create resources in default namespace to run cleanup of ns older than given time.
# 
# Set environment variables as per the requirements,
#     NAMESPACE_PREFIX='ping' (default), set 'all' to delete all non system namespaces.
#     NAMESPACE_AGE='120' (in min, default)
# 
# Note following are k8s system namespaces,
#     default, kube-node-lease, kube-public, kube-system
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-admin-serviceaccount
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin-clusterrole
  namespace: default
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-admin-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin-clusterrole
subjects:
- kind: ServiceAccount
  name: namespace-admin-serviceaccount
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-nondefault-namespaces
  namespace: default
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: '0 * * * *' # cron spec of time, every hour
  jobTemplate:
    spec:
      backoffLimit: 0 
      activeDeadlineSeconds: 120  #duration of the job
      template:
        spec:
          serviceAccountName: namespace-admin-serviceaccount # name of the service
          restartPolicy: Never
          containers:
            - name: kubectl
              image: public.ecr.aws/r2h3l6e4/delete-k8s-ns:v0.0.2
              env:
                - name: NAMESPACE_PREFIX
                  value: 'ping' # set this value to 'all' to delete all non-system ns
                - name: NAMESPACE_AGE
                  value: '120' # age in min

