apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingdelegator
spec:
  minReplicas: 2
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingdelegator
  targetCPUUtilizationPercentage: 70