apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck-cluster-health
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 90
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: cluster-healthcheck-serviceaccount
          restartPolicy: Never
          containers:
          - name: healthcheck-cluster-health
            image: public.ecr.aws/r2h3l6e4/pingcloud-services/robot-framework/dev:v1.15-release-branch-latest
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
              - /bin/bash
              - -c
              - ./robot_wrapper.py --path tests/cluster-health --include cluster-health --output cluster-health.xml
            envFrom:
            - configMapRef:
                name: cluster-health-environment-variables