apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-pingdirectory
  labels:
    role: healthcheck-pingdirectory
spec:
  selector:
    matchLabels:
      role: healthcheck-pingdirectory
  template:
    metadata:
      name: healthcheck-pingdirectory
      labels:
        role: healthcheck-pingdirectory
    spec:
      serviceAccountName: cluster-healthcheck-serviceaccount
      containers:
      - name: pingdirectory-health
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/robot-framework/dev:v1.17-release-branch-latest
        imagePullPolicy: Always
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        command:
          - /bin/bash
          - -c
          - ./robot_wrapper.py --path tests/pingdirectory --include pingDirectory --output pingDirectory.xml
        envFrom:
        - configMapRef:
            name: cluster-health-environment-variables
        resources:
          limits:
            memory: "600Mi"
            cpu: "400m"
          requests:
            memory: "400Mi"
            cpu: "200m"