# Sets up the storage class for the pingcentral servers configuration

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingcentral-gp2
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
mountOptions:
  - discard
allowVolumeExpansion: true