kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../k8s-configs/ping-cloud/test

configMapGenerator:
# Pingaccess
- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess/env_vars

# Pingfederate
- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingfederate/env_vars

# Pingdirectory
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingdirectory/env_vars

patchesJson6902:
# pingdata
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingdataconsole-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdataconsole${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingdataconsole${ENVIRONMENT}.${TENANT_DOMAIN}

# pingfederate runtime
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess runtime
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess agent
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}

# pingfederate admin
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess admin
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}

# Set a hostname for all the headless services so their endpoint IPs are published to Route53
- target:
    version: v1
    kind: Service
    name: pingdirectory
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingfederate-cluster
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingaccess-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingaccess-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

# FIXME: add this once PDO-1114 is implemented
# pingdirectory put ldaps on public and change the hostname
#- target:
#    version: v1
#    kind: Service
#    name: pingdirectory-admin
#  patch: |-
#    - op: replace
#      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
#      value: pingdirectory-admin${ENVIRONMENT}.${TENANT_DOMAIN}

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: devops-secret
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER_BASE64}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY_BASE64}
    GIT_USER: Z2l0bGFiLW1hY2hpbmUtdXNlci1hdC03MDUzNzA2MjE1Mzk=
    GIT_PASS: ZjNvd3dBSVkwYWpmZWwzWDMyUnFLeWZKS3ZEa3REZnJiUlBCQzhrY0wrcz0=

# FIXME: remove this once PDO-1114 is implemented
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: pingdirectory-admin
  $patch: delete