---

### Argo CD ###

# Deploy the git key of the CD tool to the cluster state repo
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFubG9YM1NXZ0JBcUpNS3F1RkNSVzA5ME80TmI3WXZxZmM0ZFdxNm1rU0hkRVNOR3VuZEdCCjhpTUlQdnZxczIralMvUS9XSzd4NjRZK0VEL0NVanZCdlBoZTh2aFFFZ3FuTTRoRjhFWkNITG5nQUV0YjlvVmZ6aVB2cTUKd3N2Und0VHIzZ0JwZ1kvZW02N09Felo3NXloRVZjRVpxY3NMZy9vRG5sOGNCM1F1dzhRV29QTDQwaE9KQnJZbWVnaWNwZApNRndxeGhLWWtoY1YzWGZMdHQrMjh0aHNSRmJyTjMyMmM5bXBaQUVKK0N4VUdpbmxPNENHVHdqQ3AwdlhTL2JSc1F2ODU4CmpMamxpSlBpanVIMm4wZWxQWWt4ZWRFQkpRZEljYStTWEV2R3E3VHlWamhYQStRS3ZUSmtMdnBkbTF4K0F0ZW5VOVVxMmIKMXFUME1rQW1XQmRqVlBNcHVrOVlEV2NXT0tkdW9RUTh6Nk1YRFoxVm04eFpML3lyMm5UeW1NN2tuc3lLVytQQzBld1VlegpvZFFNaVVzTWhUQndnUy9KbW1hZ0IrRGlESVhacmNpTUFhdUNWOFBDSWVRbDJCSzRlV3JBQ0kzU1ZFOFAyRW5RVkczWFJICk1CZXVTc2JDVk1jQlhQL0Y2d05ERXMxVlEzZnpoSkhYNEZnRk14bGZBQUFGaUdUR3RTNWt4clV1QUFBQUIzTnphQzF5YzIKRUFBQUdCQUo1YUY5MGxvQVFLaVRDcXJoUWtWdFBkRHVEVysyTDZuM09IVnF1cHBFaDNSRWpScnAzUmdmSWpDRDc3NnJOdgpvMHYwUDFpdThldUdQaEEvd2xJN3diejRYdkw0VUJJS3B6T0lSZkJHUWh5NTRBQkxXL2FGWDg0ajc2dWNMTDBjTFU2OTRBCmFZR1AzcHV1emhNMmUrY29SRlhCR2FuTEM0UDZBNTVmSEFkMExzUEVGcUR5K05JVGlRYTJKbm9JbktYVEJjS3NZU21KSVgKRmQxM3k3YmZ0dkxZYkVSVzZ6ZDl0blBacVdRQkNmZ3NWQm9wNVR1QWhrOEl3cWRMMTB2MjBiRUwvT2ZJeTQ1WWlUNG83aAo5cDlIcFQySk1YblJBU1VIU0hHdmtseEx4cXUwOGxZNFZ3UGtDcjB5WkM3NlhadGNmZ0xYcDFQVkt0bTlhazlESkFKbGdYClkxVHpLYnBQV0ExbkZqaW5icUVFUE0rakZ3MmRWWnZNV1MvOHE5cDA4cGpPNUo3TWlsdmp3dEhzRkhzNkhVRElsTERJVXcKY0lFdnlacG1vQWZnNGd5RjJhM0lqQUdyZ2xmRHdpSGtKZGdTdUhscXdBaU4wbFJQRDloSjBGUnQxMFJ6QVhya3JHd2xUSApBVnoveGVzRFF4TE5WVU4zODRTUjErQllCVE1aWHdBQUFBTUJBQUVBQUFHQUZrQkFwREdhUjVjWGFnQkJ6OUMvWnF2a1lGCkcxSjFaaU80Q2ovQ0V0VllWMDBlcXM1NzQ5elVHQThpREIvUTdOMm1scTBWSmI2aVdGNlJDY2hLT2krS1BKNjhoYXIvNVIKT2x1R3dGbVBCcXhUdnBiWVNFNjdoS0xtRmE0dlZ5OXphbUloN2F0SHI3NDlKdllLSENUVndLSmlhcExZTzdqWUwvS1N6aQpLbVg0QUVnNGljczZqWUp6T2I4MHJ1Y3c0OWhBTWZlNCszWXFmZHlhNEFzU1RFZDJGVDdWSnRZUEhJUm9VcVdVUVFHNUJYCkRRb2dEUGxsWmd1c0ZvZ0FxOHIxdVpWM2VFK242ZTk1cGFZVFRrTUVkM2huSmxOb00wV2poNnVDYzRBNjRodnlOY2VvSHIKcUFFVjlyUzVsVFVxZVVSTUxBczJXUFgvZlhBUFliWGtiUHZubUJsT3VDc0EzV0RMMFFqYlZUK2VRbjdCVjdnelEwVDFGMApFK0lNZm0rSnJPNUtUa201ZGZUeFMwaHJTRkp3N1JhUkdqWFB3TGNlUXNmdzJhQ25BQ0xUbVVuOVhCSkczaDV5NE1GMW5jCnNJMjlwRGZPZ3c2SmdFNk05dTcwMlFBYndqSmh5eHlmREdHUzhKUFZoY25Uak1iamprdktpa0lXTnlmaVFNemRWeEFBQUEKd1FDNURKS0pVaWNUc01odHZWdEpVOWtISEgyazh1Ly9WVEptakNZUWN2dlNpS2xhTVMraEpOSnFMSXBaYTNTMVJNeWlkSQpvSkhZSFRCN2lpV0R5RTlQVmQvaWQwaXBmdTMxRnQwRVBrSXZFdStsQ1pQdjFOQUgvQmMxZVUrbnpWdXpCNTdtakw5aDVwCmxEbENRd09pVk9BR0hPRVV0SjFscGxjYjhiVHNBeDE4MmtPRkNremJGK0hSVnRJUTdsVmFTZ0YzQ05Wdk9kbzBRbldJVHkKUlFJaEZRNFlCc0VjN042SkNFcVBPR0JXanFzdC8wNXRDM2gyd09lZ1ZUV1dEd3lkSUFBQURCQU5DZUZ2M3pwU1YxODdEcQplQUl1VnVUY2g4ZzNyMmEwbU9JeVkwZFNUMGNRYUU4SGRyNzRzUElFSk1oMng0Um92bUVMSXN1MUV6OWliN0NVZmJzUEVSClZZekpoSEluNzZDZWJjOFdiZ2p1d1VpbWRpRFhsMDNTajAzTExHV1NQR0RNZUVLT3FoTHVVZVJoeXJTbitZUnhzS3U5cEYKQ1MwWFpnVUJ4dmNMUllhNzA3Q0RGaDRxYmlJL2FrMXduclZ0YU51N3F5M3pra3Jkb1ZSMFFpU25tZXJIbTk5MVg1cGNiNApkUUxtYjBnbWR4d0dQN3V0d0d1VkYzQW1BdEdwT25LUUFBQU1FQXdsRlkzaldNNDBYV2ZJdG85TGlOSkNJMHVSK2crUzVoCmphRytzeDBXWUhQckNrdUVrd1dWQ2ZOTnAwN3N4OUlEdFFlbWt4eDlwdVpZdmw4Um9OdDJQanZ1dFduMkVHeksza0pqQXcKb3ZDZW55bmJNMys5c1hodkpwazVZNEEyRWtJUy9ZV1M3SWxWM215RWFIRkFUOC90MXk5aEVsc3Jnd1lCVnNReTk0UnhLUgpOVi9lQ3pCZ2J2R1VNVHdKbnVDN1d2ZmpaZTRjalBqbURqbGZhb2s2VXlrU2pabnhVcUpQTUo1N041clluR2k5T2czdGlRCk5KNEp3RXpFc3hTblZIQUFBQUVXRmlhR0ZzYkdGQVlXSm9ZV3hzWVMxeUFRPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

# Add argocd admin password to the data section with the bcrypt hash value.
# Ref: https://argo-cd.readthedocs.io/en/stable/faq/#i-forgot-the-admin-password-how-do-i-reset-it
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  admin.password: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFubG9YM1NXZ0JBcUpNS3F1RkNSVzA5ME80TmI3WXZxZmM0ZFdxNm1rU0hkRVNOR3VuZEdCCjhpTUlQdnZxczIralMvUS9XSzd4NjRZK0VEL0NVanZCdlBoZTh2aFFFZ3FuTTRoRjhFWkNITG5nQUV0YjlvVmZ6aVB2cTUKd3N2Und0VHIzZ0JwZ1kvZW02N09Felo3NXloRVZjRVpxY3NMZy9vRG5sOGNCM1F1dzhRV29QTDQwaE9KQnJZbWVnaWNwZApNRndxeGhLWWtoY1YzWGZMdHQrMjh0aHNSRmJyTjMyMmM5bXBaQUVKK0N4VUdpbmxPNENHVHdqQ3AwdlhTL2JSc1F2ODU4CmpMamxpSlBpanVIMm4wZWxQWWt4ZWRFQkpRZEljYStTWEV2R3E3VHlWamhYQStRS3ZUSmtMdnBkbTF4K0F0ZW5VOVVxMmIKMXFUME1rQW1XQmRqVlBNcHVrOVlEV2NXT0tkdW9RUTh6Nk1YRFoxVm04eFpML3lyMm5UeW1NN2tuc3lLVytQQzBld1VlegpvZFFNaVVzTWhUQndnUy9KbW1hZ0IrRGlESVhacmNpTUFhdUNWOFBDSWVRbDJCSzRlV3JBQ0kzU1ZFOFAyRW5RVkczWFJICk1CZXVTc2JDVk1jQlhQL0Y2d05ERXMxVlEzZnpoSkhYNEZnRk14bGZBQUFGaUdUR3RTNWt4clV1QUFBQUIzTnphQzF5YzIKRUFBQUdCQUo1YUY5MGxvQVFLaVRDcXJoUWtWdFBkRHVEVysyTDZuM09IVnF1cHBFaDNSRWpScnAzUmdmSWpDRDc3NnJOdgpvMHYwUDFpdThldUdQaEEvd2xJN3diejRYdkw0VUJJS3B6T0lSZkJHUWh5NTRBQkxXL2FGWDg0ajc2dWNMTDBjTFU2OTRBCmFZR1AzcHV1emhNMmUrY29SRlhCR2FuTEM0UDZBNTVmSEFkMExzUEVGcUR5K05JVGlRYTJKbm9JbktYVEJjS3NZU21KSVgKRmQxM3k3YmZ0dkxZYkVSVzZ6ZDl0blBacVdRQkNmZ3NWQm9wNVR1QWhrOEl3cWRMMTB2MjBiRUwvT2ZJeTQ1WWlUNG83aAo5cDlIcFQySk1YblJBU1VIU0hHdmtseEx4cXUwOGxZNFZ3UGtDcjB5WkM3NlhadGNmZ0xYcDFQVkt0bTlhazlESkFKbGdYClkxVHpLYnBQV0ExbkZqaW5icUVFUE0rakZ3MmRWWnZNV1MvOHE5cDA4cGpPNUo3TWlsdmp3dEhzRkhzNkhVRElsTERJVXcKY0lFdnlacG1vQWZnNGd5RjJhM0lqQUdyZ2xmRHdpSGtKZGdTdUhscXdBaU4wbFJQRDloSjBGUnQxMFJ6QVhya3JHd2xUSApBVnoveGVzRFF4TE5WVU4zODRTUjErQllCVE1aWHdBQUFBTUJBQUVBQUFHQUZrQkFwREdhUjVjWGFnQkJ6OUMvWnF2a1lGCkcxSjFaaU80Q2ovQ0V0VllWMDBlcXM1NzQ5elVHQThpREIvUTdOMm1scTBWSmI2aVdGNlJDY2hLT2krS1BKNjhoYXIvNVIKT2x1R3dGbVBCcXhUdnBiWVNFNjdoS0xtRmE0dlZ5OXphbUloN2F0SHI3NDlKdllLSENUVndLSmlhcExZTzdqWUwvS1N6aQpLbVg0QUVnNGljczZqWUp6T2I4MHJ1Y3c0OWhBTWZlNCszWXFmZHlhNEFzU1RFZDJGVDdWSnRZUEhJUm9VcVdVUVFHNUJYCkRRb2dEUGxsWmd1c0ZvZ0FxOHIxdVpWM2VFK242ZTk1cGFZVFRrTUVkM2huSmxOb00wV2poNnVDYzRBNjRodnlOY2VvSHIKcUFFVjlyUzVsVFVxZVVSTUxBczJXUFgvZlhBUFliWGtiUHZubUJsT3VDc0EzV0RMMFFqYlZUK2VRbjdCVjdnelEwVDFGMApFK0lNZm0rSnJPNUtUa201ZGZUeFMwaHJTRkp3N1JhUkdqWFB3TGNlUXNmdzJhQ25BQ0xUbVVuOVhCSkczaDV5NE1GMW5jCnNJMjlwRGZPZ3c2SmdFNk05dTcwMlFBYndqSmh5eHlmREdHUzhKUFZoY25Uak1iamprdktpa0lXTnlmaVFNemRWeEFBQUEKd1FDNURKS0pVaWNUc01odHZWdEpVOWtISEgyazh1Ly9WVEptakNZUWN2dlNpS2xhTVMraEpOSnFMSXBaYTNTMVJNeWlkSQpvSkhZSFRCN2lpV0R5RTlQVmQvaWQwaXBmdTMxRnQwRVBrSXZFdStsQ1pQdjFOQUgvQmMxZVUrbnpWdXpCNTdtakw5aDVwCmxEbENRd09pVk9BR0hPRVV0SjFscGxjYjhiVHNBeDE4MmtPRkNremJGK0hSVnRJUTdsVmFTZ0YzQ05Wdk9kbzBRbldJVHkKUlFJaEZRNFlCc0VjN042SkNFcVBPR0JXanFzdC8wNXRDM2gyd09lZ1ZUV1dEd3lkSUFBQURCQU5DZUZ2M3pwU1YxODdEcQplQUl1VnVUY2g4ZzNyMmEwbU9JeVkwZFNUMGNRYUU4SGRyNzRzUElFSk1oMng0Um92bUVMSXN1MUV6OWliN0NVZmJzUEVSClZZekpoSEluNzZDZWJjOFdiZ2p1d1VpbWRpRFhsMDNTajAzTExHV1NQR0RNZUVLT3FoTHVVZVJoeXJTbitZUnhzS3U5cEYKQ1MwWFpnVUJ4dmNMUllhNzA3Q0RGaDRxYmlJL2FrMXduclZ0YU51N3F5M3pra3Jkb1ZSMFFpU25tZXJIbTk5MVg1cGNiNApkUUxtYjBnbWR4d0dQN3V0d0d1VkYzQW1BdEdwT25LUUFBQU1FQXdsRlkzaldNNDBYV2ZJdG85TGlOSkNJMHVSK2crUzVoCmphRytzeDBXWUhQckNrdUVrd1dWQ2ZOTnAwN3N4OUlEdFFlbWt4eDlwdVpZdmw4Um9OdDJQanZ1dFduMkVHeksza0pqQXcKb3ZDZW55bmJNMys5c1hodkpwazVZNEEyRWtJUy9ZV1M3SWxWM215RWFIRkFUOC90MXk5aEVsc3Jnd1lCVnNReTk0UnhLUgpOVi9lQ3pCZ2J2R1VNVHdKbnVDN1d2ZmpaZTRjalBqbURqbGZhb2s2VXlrU2pabnhVcUpQTUo1N041clluR2k5T2czdGlRCk5KNEp3RXpFc3hTblZIQUFBQUVXRmlhR0ZzYkdGQVlXSm9ZV3hzWVMxeUFRPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

### Argo CD Image Updater  ###

# Deploy the git key for argocd-image-updater
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-image-updater-ssh-key
  namespace: argocd
data:
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFubG9YM1NXZ0JBcUpNS3F1RkNSVzA5ME80TmI3WXZxZmM0ZFdxNm1rU0hkRVNOR3VuZEdCCjhpTUlQdnZxczIralMvUS9XSzd4NjRZK0VEL0NVanZCdlBoZTh2aFFFZ3FuTTRoRjhFWkNITG5nQUV0YjlvVmZ6aVB2cTUKd3N2Und0VHIzZ0JwZ1kvZW02N09Felo3NXloRVZjRVpxY3NMZy9vRG5sOGNCM1F1dzhRV29QTDQwaE9KQnJZbWVnaWNwZApNRndxeGhLWWtoY1YzWGZMdHQrMjh0aHNSRmJyTjMyMmM5bXBaQUVKK0N4VUdpbmxPNENHVHdqQ3AwdlhTL2JSc1F2ODU4CmpMamxpSlBpanVIMm4wZWxQWWt4ZWRFQkpRZEljYStTWEV2R3E3VHlWamhYQStRS3ZUSmtMdnBkbTF4K0F0ZW5VOVVxMmIKMXFUME1rQW1XQmRqVlBNcHVrOVlEV2NXT0tkdW9RUTh6Nk1YRFoxVm04eFpML3lyMm5UeW1NN2tuc3lLVytQQzBld1VlegpvZFFNaVVzTWhUQndnUy9KbW1hZ0IrRGlESVhacmNpTUFhdUNWOFBDSWVRbDJCSzRlV3JBQ0kzU1ZFOFAyRW5RVkczWFJICk1CZXVTc2JDVk1jQlhQL0Y2d05ERXMxVlEzZnpoSkhYNEZnRk14bGZBQUFGaUdUR3RTNWt4clV1QUFBQUIzTnphQzF5YzIKRUFBQUdCQUo1YUY5MGxvQVFLaVRDcXJoUWtWdFBkRHVEVysyTDZuM09IVnF1cHBFaDNSRWpScnAzUmdmSWpDRDc3NnJOdgpvMHYwUDFpdThldUdQaEEvd2xJN3diejRYdkw0VUJJS3B6T0lSZkJHUWh5NTRBQkxXL2FGWDg0ajc2dWNMTDBjTFU2OTRBCmFZR1AzcHV1emhNMmUrY29SRlhCR2FuTEM0UDZBNTVmSEFkMExzUEVGcUR5K05JVGlRYTJKbm9JbktYVEJjS3NZU21KSVgKRmQxM3k3YmZ0dkxZYkVSVzZ6ZDl0blBacVdRQkNmZ3NWQm9wNVR1QWhrOEl3cWRMMTB2MjBiRUwvT2ZJeTQ1WWlUNG83aAo5cDlIcFQySk1YblJBU1VIU0hHdmtseEx4cXUwOGxZNFZ3UGtDcjB5WkM3NlhadGNmZ0xYcDFQVkt0bTlhazlESkFKbGdYClkxVHpLYnBQV0ExbkZqaW5icUVFUE0rakZ3MmRWWnZNV1MvOHE5cDA4cGpPNUo3TWlsdmp3dEhzRkhzNkhVRElsTERJVXcKY0lFdnlacG1vQWZnNGd5RjJhM0lqQUdyZ2xmRHdpSGtKZGdTdUhscXdBaU4wbFJQRDloSjBGUnQxMFJ6QVhya3JHd2xUSApBVnoveGVzRFF4TE5WVU4zODRTUjErQllCVE1aWHdBQUFBTUJBQUVBQUFHQUZrQkFwREdhUjVjWGFnQkJ6OUMvWnF2a1lGCkcxSjFaaU80Q2ovQ0V0VllWMDBlcXM1NzQ5elVHQThpREIvUTdOMm1scTBWSmI2aVdGNlJDY2hLT2krS1BKNjhoYXIvNVIKT2x1R3dGbVBCcXhUdnBiWVNFNjdoS0xtRmE0dlZ5OXphbUloN2F0SHI3NDlKdllLSENUVndLSmlhcExZTzdqWUwvS1N6aQpLbVg0QUVnNGljczZqWUp6T2I4MHJ1Y3c0OWhBTWZlNCszWXFmZHlhNEFzU1RFZDJGVDdWSnRZUEhJUm9VcVdVUVFHNUJYCkRRb2dEUGxsWmd1c0ZvZ0FxOHIxdVpWM2VFK242ZTk1cGFZVFRrTUVkM2huSmxOb00wV2poNnVDYzRBNjRodnlOY2VvSHIKcUFFVjlyUzVsVFVxZVVSTUxBczJXUFgvZlhBUFliWGtiUHZubUJsT3VDc0EzV0RMMFFqYlZUK2VRbjdCVjdnelEwVDFGMApFK0lNZm0rSnJPNUtUa201ZGZUeFMwaHJTRkp3N1JhUkdqWFB3TGNlUXNmdzJhQ25BQ0xUbVVuOVhCSkczaDV5NE1GMW5jCnNJMjlwRGZPZ3c2SmdFNk05dTcwMlFBYndqSmh5eHlmREdHUzhKUFZoY25Uak1iamprdktpa0lXTnlmaVFNemRWeEFBQUEKd1FDNURKS0pVaWNUc01odHZWdEpVOWtISEgyazh1Ly9WVEptakNZUWN2dlNpS2xhTVMraEpOSnFMSXBaYTNTMVJNeWlkSQpvSkhZSFRCN2lpV0R5RTlQVmQvaWQwaXBmdTMxRnQwRVBrSXZFdStsQ1pQdjFOQUgvQmMxZVUrbnpWdXpCNTdtakw5aDVwCmxEbENRd09pVk9BR0hPRVV0SjFscGxjYjhiVHNBeDE4MmtPRkNremJGK0hSVnRJUTdsVmFTZ0YzQ05Wdk9kbzBRbldJVHkKUlFJaEZRNFlCc0VjN042SkNFcVBPR0JXanFzdC8wNXRDM2gyd09lZ1ZUV1dEd3lkSUFBQURCQU5DZUZ2M3pwU1YxODdEcQplQUl1VnVUY2g4ZzNyMmEwbU9JeVkwZFNUMGNRYUU4SGRyNzRzUElFSk1oMng0Um92bUVMSXN1MUV6OWliN0NVZmJzUEVSClZZekpoSEluNzZDZWJjOFdiZ2p1d1VpbWRpRFhsMDNTajAzTExHV1NQR0RNZUVLT3FoTHVVZVJoeXJTbitZUnhzS3U5cEYKQ1MwWFpnVUJ4dmNMUllhNzA3Q0RGaDRxYmlJL2FrMXduclZ0YU51N3F5M3pra3Jkb1ZSMFFpU25tZXJIbTk5MVg1cGNiNApkUUxtYjBnbWR4d0dQN3V0d0d1VkYzQW1BdEdwT25LUUFBQU1FQXdsRlkzaldNNDBYV2ZJdG85TGlOSkNJMHVSK2crUzVoCmphRytzeDBXWUhQckNrdUVrd1dWQ2ZOTnAwN3N4OUlEdFFlbWt4eDlwdVpZdmw4Um9OdDJQanZ1dFduMkVHeksza0pqQXcKb3ZDZW55bmJNMys5c1hodkpwazVZNEEyRWtJUy9ZV1M3SWxWM215RWFIRkFUOC90MXk5aEVsc3Jnd1lCVnNReTk0UnhLUgpOVi9lQ3pCZ2J2R1VNVHdKbnVDN1d2ZmpaZTRjalBqbURqbGZhb2s2VXlrU2pabnhVcUpQTUo1N041clluR2k5T2czdGlRCk5KNEp3RXpFc3hTblZIQUFBQUVXRmlhR0ZzYkdGQVlXSm9ZV3hzWVMxeUFRPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

#Argocd slack token

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-notifications-secret
data:
  slack-token: dXNpbmdfZGVmYXVsdF9pbnZhbGlkX3Rva2Vu
  
---

# Add argocd admin password for argocd-image-updater.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
data:
  argocd.token: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="

---

# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: dW51c2Vk

---

# In order to change the PingCentral admin password, 2 rollouts are necessary. 
#
# 1. On the 1st rollout, change the PC_ADMIN_USER_PASSWORD as appropriate and the 
#    LAST_UPDATE_REASON for PingCentral. This will cause a rollout/restart of
#    the PingCentral pod.
# 2. On the 2nd rollout, change the OLD_PC_ADMIN_USER_PASSWORD to match the 
#.   PC_ADMIN_USER_PASSWORD. This will cause an update of the secret. 
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords

---

### Licenses ###

# Add pingcentral.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingcentral-license
type: Opaque

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nr-license-key
  namespace: elastic-stack-logging
data:
  NEW_RELIC_LICENSE_KEY: dW51c2Vk
