########################################################################################################################
# Customer parameters that are shared by multiple apps
########################################################################################################################

########################################################
# Multi-region parameters
########################################################
isMultiCluster: false

# primaryRegion is the primary AWS region name
# the primary region should have the same value for region and primaryRegion
primaryRegion: "us-west-2"

# primaryDnsZone is the primary dns zone for customer for region
primaryDnsZone: "abhalla-secondary.ping-demo.com"

# primaryTenantDomain is the primary domain suffix for customer for region
# the primary region should have the same value for tenantDomain and primaryTenantDomain
primaryTenantDomain: "abhalla-secondary.ping-demo.com"

# secondaryTenantDomains is an optional comma-separated list of the tenant domain suffixes of secondary regions used
# for PingFederate adaptive clustering using the JGroups DNS_PING discovery protocol:
#
#   - Do NOT include the primary tenant domain in the list
#   - Do NOT include the CDE prefix in the domain name
#
# For example, if the primary domain is "tuna.us1.ping-preview.cloud", then set it
# to "tuna.eu1.ping-preview.cloud,tuna.au1.ping-preview.cloud" to specify secondary
# domains in regions eu1 and au1.
#
# NOTES:
#   - Only used in multi-cluster environments. If provided, PF will be configured with DNS_PING.
#   - It is recommended that SECONDARY_TENANT_DOMAINS be set apriori, even before the
#     secondary regions are created to avoid pod rollouts. DNS_PING will simply ignore
#     unreachable domains. If it is not set beforehand, then all servers in the PF
#     cluster (admin and engines) must be re-rolled to pick up the change.
secondaryTenantDomains: ""

# globalTenantDomain is the region-independent URL used for DNS failover/routing
globalTenantDomain: "global.abhalla-secondary.ping-demo.com"


########################################################
# S3 buckets
########################################################
# pingArtifactRepoUrl is the ping-hosted common artifacts URL
pingArtifactRepoUrl: "https://ping-artifacts.s3-us-west-2.amazonaws.com"

# logArchiveUrl is the customer-specific log URL for region
logArchiveUrl: "ssm://abhalla-secondary/pcpt/service/storage/logs/uri"

# backupUrl is the customer-specific backup URL for region
backupUrl: "ssm://abhalla-secondary/pcpt/service/storage/backup/uri"


########################################################
# Miscellaneous ping-cloud-base variables
########################################################
# pingCloudNamespace is the namespace where Ping apps are deployed
pingCloudNamespace: "ping-cloud"

# k8sGitUrl is the ping-cloud-base git URL for base Kubernetes manifests
k8sGitUrl: "git@github.com:AnkitBhalla22/abhalla-ping.git"

# k8sGitBranch is the ping-cloud-base git branch for base Kubernetes manifests
k8sGitBranch: "pdo_4388"

# ecrRegistryName is the name of the Docker image registry
ecrRegistryName: "public.ecr.aws/r2h3l6e4"

# ecr_env is the suffix used to denote to use dev image repositories
ecrEnv: "/dev"

# clusterName is the eks cluster name
clusterName: "abhalla-secondary"

# serverProfileUrl is the git URL for the profile repo
serverProfileUrl: "ssh://AIDA2IO25QZRQC5SE4FL5@git-codecommit.us-west-2.amazonaws.com/v1/repos/abhalla-secondary-profile-repo"

# serverProfileBranch is the git branch for the profile repo
serverProfileBranch: "customer-hub"

# userBaseDN is the variable used by Ping products
userBaseDN: "dc=example,dc=com"

# Multiple Backend IDs
userBackendId2: "userRoot_2"
userBackendId3: "userRoot_3"
userBackendId4: "userRoot_4"
userBackendId5: "userRoot_5"


# Multiple Backend IDs Base DNs
userBaseDN2: ""
userBaseDN3: ""
userBaseDN4: ""
userBaseDN5: ""

########################################################
# Environment-specific variables
########################################################
# environmentType is used by server profile hooks
environmentType: "customer-hub"

# env is used by Kubernetes manifests
env: "customer-hub"

isBelugaEnv: true


########################################################
# DevOps License environment variables
########################################################
pingIdentityDevopsUser: "?"
pingIdentityDevopsKey: "?"


########################################################
# Ping image tags
########################################################
pingaccessImageTag: "v1.18-release-branch-latest"
pingaccessWasImageTag: "v1.18-release-branch-latest"
pingfederateImageTag: "v1.18-release-branch-latest"
pingdirectoryImageTag: "v1.18-release-branch-latest"
pingdelegatorImageTag: "v1.18-release-branch-latest"
pingcentralImageTag: "v1.18-release-branch-latest"
pingdatasyncImageTag: "v1.18-release-branch-latest"
metadataImageTag: "v1.18-release-branch-latest"
bootstrapImageTag: "v1.18-release-branch-latest"
healthcheckImageTag: "v1.18-release-branch-latest"
p14cIntegrationImageTag: "v1.18-release-branch-latest"


########################################################
# Public hostnames
########################################################
pdPrimaryPublicHostname: "pingdirectory-admin.${PRIMARY_TENANT_DOMAIN}"
pfAdminPublicHostname: "pingfederate-admin.${PRIMARY_TENANT_DOMAIN}"
pfAdminApiPublicHostname: "pingfederate-admin-api.${PRIMARY_TENANT_DOMAIN}"
paAdminPublicHostname: "pingaccess-admin.${PRIMARY_TENANT_DOMAIN}"
paAdminApiPublicHostname: "pingaccess-admin-api.${PRIMARY_TENANT_DOMAIN}"
pawasAdminPublicHostname: "pingaccess-was-admin.${PRIMARY_TENANT_DOMAIN}"
pcAdminPublicHostname: "pingcentral-admin.${PRIMARY_TENANT_DOMAIN}"
pcAdminPrivateSiteHostname: "pingcentral.abhalla-secondary.ping-demo.com"
pdClusterPublicHostname: "pingdirectory-cluster.${PRIMARY_TENANT_DOMAIN}"
pfClusterPublicHostname: "pingfederate-cluster.${PRIMARY_TENANT_DOMAIN}"
paClusterPublicHostname: "pingaccess-cluster.${PRIMARY_TENANT_DOMAIN}"
pawasClusterPublicHostname: "pingaccess-was-cluster.${PRIMARY_TENANT_DOMAIN}"

# Ping engine hostname variables
pdPublicHostname: "pingdirectory-admin.${TENANT_DOMAIN}"
pdHttpPublicHostname: "pingdirectory.${TENANT_DOMAIN}"
pdDelegatorPublicHostname: "pingdelegator.${TENANT_DOMAIN}"
pdDelegatorPublicPort: 443
pfEnginePublicHostname: "pingfederate.${TENANT_DOMAIN}"
paEnginePublicHostname: "pingaccess.${TENANT_DOMAIN}"
pawasEnginePublicHostname: "pingaccess-was.${TENANT_DOMAIN}"

prometheusPublicHostname: "prometheus.${TENANT_DOMAIN}"
grafanaPublicHostname: "monitoring.${TENANT_DOMAIN}"
kibanaPublicHostname: "logs.${TENANT_DOMAIN}"
argocdPublicHostname: "argocd.${TENANT_DOMAIN}"

healthcheckHttpbinPawasPublicHostname: "healthcheck-httpbin-pa-was.${TENANT_DOMAIN}"
healthcheckHttpbinPaPublicHostname: "healthcheck-httpbin-pa.${TENANT_DOMAIN}"


#### FEATURE FLAGS #####################################################################################################
# Set to true to enable, most are disabled by default
# Please follow runbook instructions for the given feature flag to enable/disable

# !!! Provisioning for PingFederate is not yet available for multi-region customers !!!
# Runbook: https://confluence.pingidentity.com/display/PingCloud/How+to+Enable+and+Configure+PingFederate+Provisioning
pfProvisioningEnabled: false

radiusProxyEnabled: false

external_ingress_enabled: true
########################################################################################################################




########################################################################################################################
#TODO: Are these needed anymore now that we're using values files?
# If they are needed uncomment & move to the 1st section
# If they are still commented out when we get to PDO-4842, they will be deleted
########################################################################################################################
# kustomizeBase: prod/x-small

# ansibleBelugaImageTag: v1.18-release-branch-latest

# clusterNameLc: abhalla-secondary # Helm has a "lower" function that can be used with clusterName


########################################################################################################################
#TODO: Move these to app values.yaml files as apps migrate
# If they are needed by more than 1 app, move to the 1st section
########################################################################################################################
# pgoBackupBucketName is the customer-specific pgo bucket name for region
pgoBackupBucketName: "not_set"

############################################################
# Platform event queue and SSM variables
############################################################
platformEventQueueName: "v2_platform_event_queue.fifo"
platformEventQueuePollBatchSize: 1
platformEventQueuePollIntervalSeconds: 2
orchAPISSMPathPrefix: "/pcpt/orch-api"
serviceSSMPathPrefix: "/abhalla-secondary/pcpt/service"

############################################################
# Cluster state repo details
############################################################
# knownHostsClusterStateRepo is the known-hosts file to trust the cluster state repo server for git/ssh cloning
knownHostsClusterStateRepo: "|1|Fap3yPuBIMOAY0tazjSeuf8kqAI=|S4G50yuzkpWa8w7GPvoCfbtrnXY= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqyQh/szYdP7ykDdwp8pWMgrFmuXU4mEf27Wzz6QcR/ZJsIRVCdslVjmt9RA1ljanAVPI8zjp/oI6NPICh8l638vRLt8lFbNMfMMfkzxiIXs0mLAuQ2XSbRglPDF4mAQ7C+oD/B01XXKWU4Vack37i0R9RMtkl3spFB8Hq7HJi4/wy87U7FMHfjHWYXr3GAOg1PfRyTAyHij0XXuBhxzz1vMoiI5DkgH8CKuKf+AmW5KHxKX3zPCoKe7nDw3/Re4ghYhc34ldOSZlQin/dIyT/GQy0ayRWGXc0KB2ijrDCxd4N4INBhdqCRDPwkxwqVRUToBFw6Q1zBdlVlK5ViFEV"

# clusterStateRepoUrl is the Cluster State Repo URL
clusterStateRepoUrl: "ssh://AIDA2IO25QZRQC5SE4FL5@git-codecommit.us-west-2.amazonaws.com/v1/repos/abhalla-secondary-cluster-state-repo"

# clusterStateRepoBranch is the Cluster State Repo branch
clusterStateRepoBranch: "customer-hub"

# appResyncSeconds is the application reconciliation timeout in seconds for ArgoCD, i.e. how frequently
# ArgoCD should poll the cluster-state-repo for changes. To disable reconciliation set it to 0.
appResyncSeconds: 60

# Current app logs destination (True :  CW, False :  ELK)
legacyLogging: False

############################################################
# Lets Encrypt server
############################################################
letsEncryptServer: "https://acme-v02.api.letsencrypt.org/directory"

############################################################
# PingFederate variables for environment
############################################################
pfPdBindPort: 1636
pfPdBindProtocol: "ldaps"
pfPdBindUseSsl: true

pfMinHeap: 3072m
pfMaxHeap: 3072m
pfMinYgen: 1536m
pfMaxYgen: 1536m

# This variable's value will make it onto the branding for the PF admin console and
# will include the name of the environment and the region where it's deployed.
pfAdminConsoleEnvironment: "customer-hub-us-west-2"

############################################################
# PingAccess variables for environment
############################################################
pawasMinHeap: 2048m
pawasMaxHeap: 2048m
pawasMinYgen: 1024m
pawasMaxYgen: 1024m
pawasGcoption: -XX:+UseParallelGC

paMinHeap: 1024m
paMaxHeap: 1024m
paMinYgen: 512m
paMaxYgen: 512m
paGcoption: -XX:+UseParallelGC

# Retention time for Prometheus. Could be set in years(y), weeks(w), days(d), hours(h), minutes(m) or seconds(s)
prometheusRetentionTime: "15d"

# Commands and schedules to obtain users count. Values should be in single quotes. Schedules should be in cron format. Command should return only numeric value(int\float)
prometheusUserCount1Command: 'echo 0'
prometheusUserCount1Schedule: '* * * * *'
prometheusUserCount2Command: 'echo 0'
prometheusUserCount2Schedule: '* * * * *'
prometheusUserCount3Command: 'echo 0'
prometheusUserCount3Schedule: '* * * * *'
prometheusUserCount4Command: 'echo 0'
prometheusUserCount4Schedule: '* * * * *'

# Variable to have ping-cloud namespace in prometheus-job-exporter
prometheusPingNamespace: "ping-cloud"

# Default argo-events notification configuration
notificationEnabled: false
slackChannel: "nowhere"
notificationEndpoint: "http://webhook-eventsource-svc.argo-events:12999/notification"

# Prometheus argo-events notification configuration
promNotificationEnabled: true
promSlackChannel: "nowhere"

# Variables used by argocd-image-updater to automatically update the container images managed by ArgoCD
imageTagPrefix: "pdo_4388"
imageList: "apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingfederate,apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingaccess,apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingaccess-was"

# Dashboards repo variables
dashRepoUrl: "https://github.com/pingidentity/ping-cloud-dashboards"
dashRepoBranch: "v1.18-dev-branch"
