# For reference, please see the documentation in the root of the repo docs/StorageClass.md
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingaccess-was-gp3
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"
  type: gp3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-2
    namespace: ping-cloud-calvincarter
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pingdirectory-gp3
  resources:
    requests:
      storage: 2Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: backup-dir-pingdirectory-0

---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete

---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ebs-volume-snapshot
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: backup-dir-pingdirectory-0