apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
    config:  # Everything related to the securityconfig
      securityConfigSecret:
        name: opensearch-securityconfig # Name of the secret that contains the securityconfig files
      adminCredentialsSecret:
        name: opensearch-admin-credentials # Name of a secret that contains username/password for admin access
  general:
    serviceName: opensearch-cluster
    version: 2.8.0
    image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/opensearch/dev:v1.19-release-branch-latest
    setVMMaxMapCount: true
    additionalConfig:
      node.search.cache.size: 500m
      cluster.max_shards_per_node: "10000"
      prometheus.indices: "false"
  dashboards:
    enable: true
    version: 2.8.0
    opensearchCredentialsSecret:
      name: opensearch-dashboard-credentials
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: hot
      labels:
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch-cluster-hot
      replicas: 3
      diskSize: "8Gi"
      jvm: -Xmx3000M -Xms3000M
      pdb:
        enable: true
        maxUnavailable: 1
      additionalConfig:
        node.attr.temp: "hot"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - opensearch-cluster-hot
              topologyKey: kubernetes.io/hostname
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
            - "ReadWriteOnce"
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 4Gi
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
        - "remote_cluster_client"
        - "search"
    - component: warm
      labels:
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch-cluster-warm
      replicas: 3
      diskSize: "140Gi"
      jvm: -Xmx3g -Xms3g
      pdb:
        enable: true
        maxUnavailable: 1
      additionalConfig:
        node.attr.temp: "hot"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - opensearch-cluster-warm
              topologyKey: kubernetes.io/hostname
      persistence:
        pvc:
          storageClass: opensearch-sc1
          accessModes:
            - "ReadWriteOnce"
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 4Gi
      roles:
        - "remote_cluster_client"
        - "data"