kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- configs
- security_configs
- service.yaml
- index-templates
- storageclass.yaml
- ism-policies
- alerts
- notifications
- bootstrap.yaml
- cluster.yaml