apiVersion: v1
kind: ServiceAccount
metadata:
  name: pf-ik-deployeraccount

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pf-ik-deployer-role
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - get
      - watch
      - create
      - update

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pf-ik-deployeraccount-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pf-ik-deployeraccount-role
subjects:
  - kind: ServiceAccount
    name: pf-ik-deployeraccounteaccount
