namespace: postgres-operator

commonLabels:
  app.kubernetes.io/name: pgo
  # The version below should match the version on the PostgresCluster CRD
  app.kubernetes.io/version: 5.3.1

resources:
- ../crd
- ../rbac/cluster
- ../manager

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.3.1-0
- name: postgres-operator-upgrade
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade
  newTag: ubi8-5.3.1-0
