apiVersion: batch/v1
kind: Job
metadata:
  name: pingfederate-admin-configurator
spec:
  template:
    spec:
      serviceAccount: pf-script-serviceaccount
      containers:
      - name: pingfederate-admin-configurator
        image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/p14c-integration:v1.0.5-pdo-2204
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: [ 'python3', '-u', '/app/src/pingfederate_admin_configurator.py' ]
      restartPolicy: Never
  backoffLimit: 4