kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
  - ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/monitoring/prometheus?ref=${K8S_GIT_BRANCH}
  - ${DASH_REPO_URL}/grafana?ref=${DASH_REPO_BRANCH}
