apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-csd-upload
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingfederate-periodic-csd-upload
            # Required because new GSA images run as non-root by default, and P1AS does not work with non-root user yet.
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
            # FIXME: switch to stable version once GSA team publishes
            image: pingcloud-virtual.jfrog.io/pingidentity/pingfederate:10.2.4-edge
            command:
            - /opt/in/backup-csd-data.sh
            env:
            - name: CSD_POD_ROLE
              value: "pingfederate-engine"
            - name: CSD_CONTAINER_NAME
              value: "pingfederate"
            envFrom:
            - configMapRef:
                name: pingfederate-environment-variables
            volumeMounts:
            - name: pingfederate-periodic-csd-upload
              mountPath: /opt/in/backup-csd-data.sh
              subPath: backup-csd-data.sh
          volumes:
          - name: pingfederate-periodic-csd-upload
            configMap:
              name: pingfederate-periodic-csd-upload
              defaultMode: 0555
