_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: true # Enabled for prometheus scrape with limited access
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    kibana:
      index: .kibana
      multitenancy_enabled: false
      server_username: kibanaserver
    authc:
      # OpenSearch Dashboards requires that the internal OpenSearch Dashboards server user can authenticate through
      # HTTP basic authentication, so we must configure two authentication domains. For OpenID Connect, the HTTP basic
      # domain has to be placed first in the chain. (HTTP is set to `order: 0`, and OIDC is `order: 1`)
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: name
            roles_key: groups
            openid_connect_url: https://auth-staging.pingone.com/b9b5b6f5-3440-4adc-8dc4-46593f1263f7/as/.well-known/openid-configuration
        authentication_backend:
          type: noop
