kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

secretGenerator:
  - name: opensearch-securityconfig-tmm8d5mm47
    type: Opaque
    files:
      - action_groups.yml
      - audit.yml
      - config.yml
      - internal_users.yml
      - nodes_dn.yml
      - roles.yml
      - roles_mapping.yml
      - tenants.yml
      - whitelist.yml

generatorOptions:
 disableNameSuffixHash: true