apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-credentials
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: Prune=false
data:
  username: YWRtaW4K
  password: Qlg1T1lwVk16Y1o5d0R5UHJRS1o4cUJ1VQ==