apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"
  target:
    kind: CustomResourceDefinition
    name: grafanas.grafana.integreatly.org
    version: v1
- patch: "- op: add\n  path: /metadata/annotations/argocd.argoproj.io~1sync-options\n
    \ value: \"ServerSideApply=true\"  "
  target:
    kind: CustomResourceDefinition
    name: grafanadashboards.grafana.integreatly.org
    version: v1
- patch: "- op: add\n  path: /metadata/annotations/argocd.argoproj.io~1sync-options\n
    \ value: \"ServerSideApply=true\"  "
  target:
    kind: CustomResourceDefinition
    name: grafanadatasources.grafana.integreatly.org
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "ServerSideApply=true"
  target:
    kind: CustomResourceDefinition
    name: grafanafolders.grafana.integreatly.org
    version: v1
