kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    $patch: delete
spec:
  type: ExternalName
  externalName: prometheus-central.${PRIMARY_DNS_ZONE}
  $patch: replace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
$patch: delete
---
