kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# This will roll out updates to all Ping applications in one fell swoop. This is preferred for simple updates as it's
# faster. However, when Ping application versions are changing between Beluga versions, a more granular rollout may be
# necessary to maintain app dependencies. Refer to the following section on how to do that.
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}?ref=${K8S_GIT_BRANCH}

# For granular rollout of applications, comment out the above line in lieu of the one below. When all applications
# are rolled out in the appropriate dependency order, reset the change back to how it was.
# - granular-rollout.yaml

configMapGenerator:

### PD topology descriptor.json file. Only required in multi-region deployments. ###
### Refer to profiles/pingdirectory/topology/descriptor-profiles.json.sample for more details. ###
- name: topology-descriptor
  behavior: merge
  files:
  - pingdirectory/descriptor.json

patchesStrategicMerge:

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

patchesJson6902:

# pingcloud-metadata ingress
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: metadata-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: metadata.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: metadata.${DNS_ZONE}