kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# PingCloud common resources
- pingcommon

# PingDirectory resources
- pingdirectory

# The following Ping applications are divided into their individual components to facilitate phased rollouts of
# applications that depend on each other. For example, pingaccess-was admin should be updated before pingaccess-was
# engines, so 2 separate rollouts are necessary. On the 1st rollout, comment out the "- pingaccess-was/engine" line,
# and on the 2nd rollout, uncomment it. It's okay to leave the "- pingaccess-was/admin" uncommented out on the 2nd
# rollout since its deployment should be idempotent. After all the application are updated, make sure to include all
# applications in subsequent rollouts.

# PingAccess common, admin and engine resources
- pingaccess/common
- pingaccess/admin
- pingaccess/engine

# PingAccess WAS common, admin and engine resources
- pingaccess-was/common
- pingaccess-was/admin
- pingaccess-was/engine

# PingFederate common, admin and engine resources
- pingfederate/common
- pingfederate/admin
- pingfederate/engine

configMapGenerator:

### PD topology descriptor.json file. Only required in multi-region deployments. ###
### Refer to profiles/pingdirectory/topology/descriptor-profiles.json.sample for more details. ###
- name: topology-descriptor
  behavior: merge
  files:
  - pingdirectory/descriptor.json

patchesStrategicMerge:

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

patchesJson6902:

# pingcloud-metadata ingress
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: metadata-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: metadata.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: metadata.${DNS_ZONE}