apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingfederate
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingfederate
  targetCPUUtilizationPercentage: 70
