apiVersion: batch/v1
kind: Job
metadata:
  name: p1as-oauth
  labels:
    role: p1as-oauth
spec:
  # 24-hour TTL for debugging
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      serviceAccountName: p1as-bootstrap
      containers:
      # Set up PingOne SSO
      - name: p1as-oauth
        image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-services/p14c-integration:PDO-6287-osd-sso
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: p1as-bootstrap
        command:
          - /bin/sh
          - -c
          - python3 -u /app/oauth_client_services_controller.py --app opensearch
      restartPolicy: Never
      tolerations:
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Equal
          value: core
