### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave this customization in this file. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-environment-variables
  namespace: ping-cloud