kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../base
- ../../base/pingdirectory/base
- ../../base/pingfederate/aws

patchesStrategicMerge:
- pingdirectory/limits.yaml
- pingfederate/limits.yaml