kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../base
- ../../base/pingdirectory/aws
- ../../base/pingfederate/aws

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - pingdirectory/env_vars

patchesStrategicMerge:
- pingdirectory/limits.yaml
- pingfederate/limits.yaml