apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: prometheus
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  objstore.yml: |
    type: S3