apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was-admin
        resources:
          requests:
            memory: 4Gi
            cpu: 1
          limits:
            memory: 5Gi
            cpu: 1