kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base

patches:
- path: add-cloud-provider-arg.yaml
  target:
    group: apps
    kind: Deployment
    name: cluster-autoscaler
    namespace: kube-system
    version: v1
    