kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  labels:
    k8s-app: fluent-bit

configMapGenerator:
  - name: fluent-bit-config
    files:
      - fluent-bit.conf
    literals:
      - log.level=error
      - read.head=True
      - read.tail=Off
      - newrelic_cluster_name=${NEW_RELIC_ENVIRONMENT_NAME}
  - name: fluent-bit-parsers
    files:
      - parsers.conf

resources:
  - pipelines
