kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess-WAS license and common environment variables that is shared between admin and runtime engines
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess-was?ref=${K8S_GIT_BRANCH}

generatorOptions:
  disableNameSuffixHash: true
