kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Apply PingDirectory deployment resources
resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingdirectory/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingdirectory${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingdirectory${ECR_ENV}
  newTag: ${PINGDIRECTORY_IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingdirectory-last-update-config
  target:
    group: apps
    kind: StatefulSet
    name: pingdirectory
    version: v1
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdirectory.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingdirectory.${DNS_ZONE}
  target:
    group: networking.k8s.io
    kind: Ingress
    name: pingdirectory-http-ingress
    version: v1
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-cluster.${DNS_ZONE}
  target:
    kind: Service
    name: pingdirectory
    version: v1
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-admin.${DNS_ZONE}
  target:
    kind: Service
    name: pingdirectory-admin
    version: v1
