apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
spec:
  template:
    spec:
      containers:
      - name: pingaccess-admin
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 2
