# This defines the Ping DataSync deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectoryproxy
  labels:
    role: pingdirectoryproxy-server
spec:
  selector:
    matchLabels:
      role: pingdirectoryproxy-server
  replicas: 1
  serviceName: pingdirectoryproxy-admin
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      name: pingdirectoryproxy
      labels:
        role: pingdirectoryproxy-server
      annotations:
        lastUpdateReason: "NA"
    spec:
      serviceAccountName: ping-serviceaccount
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: pingdirectoryproxy-init
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/bitnami/kubectl:1.23.0
        imagePullPolicy: IfNotPresent
        command:
          - /copy-dependencies.sh
        volumeMounts:
          - name: ssh-dir
            mountPath: /.ssh
          - name: data-dir
            mountPath: /data
          - name: ssh-id-key-secret
            mountPath: /id_rsa
            subPath: id_rsa
          - name: known-hosts-config
            mountPath: /known_hosts
            subPath: known_hosts
          - name: pingdirectoryproxy-init
            mountPath: /copy-dependencies.sh
            subPath: copy-dependencies.sh
          - name: pingdirectoryproxy-init
            mountPath: /utils.lib.sh
            subPath: utils.lib.sh
          - name: pingdirectoryproxy-init
            mountPath: /logger.lib.sh
            subPath: logger.lib.sh
        envFrom:
          - configMapRef:
              name: pingdirectoryproxy-environment-variables
      containers:
      - name: pingdirectoryproxy
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        image: public.ecr.aws/r2h3l6e4/pingidentity/pingdirectoryproxy:2301-9.2.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "4Gi"
            cpu: "2"
        readinessProbe:
          exec:
            command: [/opt/readiness.sh]
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: [/opt/liveness.sh]
          initialDelaySeconds: 90
          periodSeconds: 30
          failureThreshold: 5
          timeoutSeconds: 5
        ports:
          - name: ldap
            containerPort: 1389
          - name: ldaps
            containerPort: 1636
          - name: https
            containerPort: 1443
        env:
          - name: ROOT_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingdirectoryproxy-passwords
                key: root-user-password
        envFrom:
          - configMapRef:
              name: pingdirectoryproxy-environment-variables
          - configMapRef:
              name: pingcommon-environment-variables
        volumeMounts:
          - name: ssh-dir
            mountPath: /home/ping/.ssh
          - name: out-dir
            mountPath: /opt/out
          - name: data-dir
            mountPath: /usr/local/bin/kubectl
            subPath: kubectl
          - name: data-dir
            mountPath: /opt/staging/ds_env_vars
            subPath: ds_env_vars
          - name: data-dir
            mountPath: /opt/staging/hooks/logger.lib.sh
            subPath: logger.lib.sh
          - name: topology-descriptor
            mountPath: /opt/staging/topology/descriptor.json
            subPath: descriptor.json
          - name: pingdirectoryproxy-passwords
            mountPath: /usr/local/secrets
            readOnly: true
          - name: pingdirectory-license
            mountPath: /opt/in/instance/conf/PingDirectory.lic
            subPath: PingDirectory.lic
      securityContext:
        fsGroup: 9999
      volumes:
        - name: ssh-dir
          emptyDir: {}
        - name: data-dir
          emptyDir: {}
        - name: pingdirectoryproxy-init
          configMap:
            name: pingcommon-init
            defaultMode: 0555
        - name: topology-descriptor
          configMap:
            name: topology-descriptor
            optional: true
            defaultMode: 0644
        - name: ssh-id-key-secret
          secret:
            secretName: ssh-id-key-secret
            optional: true
            defaultMode: 0400
        - name: known-hosts-config
          configMap:
            name: known-hosts-config
            optional: true
            defaultMode: 0644
        - name: out-dir
          persistentVolumeClaim:
            claimName: out-dir
        - name: pingdirectoryproxy-passwords
          secret:
            secretName: pingdirectoryproxy-passwords
            optional: true
            defaultMode: 0440
        - name: pingdirectory-license
          secret:
            secretName: pingdirectory-license
            optional: true
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: out-dir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: pingdirectoryproxy-gp2
        resources:
          requests:
            storage: 20Gi