# Sets up the storage class for the pingdirectoryproxy server (data and configuration)

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdirectoryproxy-gp2
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  type: gp2
  fsType: ext4
mountOptions:
  - discard
allowVolumeExpansion: true