apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: enrichment-job
spec:
  # triggers every 10 minutes
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: enrichment
          restartPolicy: OnFailure
          
          containers:

          - name: enrichment-job
            image: 7es7/enrichment-bootstrap:latest   # gcr.io/ping-identity/ping-cloud-enrichment-bootstrap/ping-cloud-enrichment-bootstrap:7.8.0.1
            imagePullPolicy: Always
            workingDir: /scripts
            command: ["sh", '$(CONTAINER_NAME).sh']

            securityContext:
              privileged: true

            env:
            - name: CONTAINER_NAME
              value: "enrichment-job"
            - name:  ENRICHMENT_TOR_FEED_URL
              value: "https://check.torproject.org/exit-addresses"
            - name:  ENRICHMENT_ALIEN_VAULT_FEED_URL
              value: "https://reputation.alienvault.com/reputation.generic"
            - name:  ENRICHMENT_FILEPATH
              value: "/enrichment-shared-volume/enrichment-cache/"
            - name: LOGSTASH_URL
              value: "http://logstash-elastic"
            - name: LOGSTASH_PORT
              value: "20510"
            - name:  PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONIOENCODING
              value: "UTF-8"
            
            volumeMounts:
            - name: enrichment-shared-volume
              mountPath: /enrichment-shared-volume
              readOnly: false

          volumes:
          - name: enrichment-shared-volume
            nfs:
              server: ${EFS_FILESYSTEM_ID}.efs.${REGION}.amazonaws.com
              path: /
