apiVersion: v1
kind: ServiceAccount
metadata:
  name: enrichment
  labels:
    app: enrichment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enrichment
  labels:
    app: enrichment
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "update", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enrichment
roleRef:
  kind: ClusterRole
  name: enrichment
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: enrichment

---
apiVersion: v1
kind: Secret
metadata:
  name: elk-secrets
type: Opaque
data:
  # To convert your credentials to base64 format, use the following:
  # printf '<USERNAME_OR_PASSWORD>' | base64

  # Elasticsearch bootstrap username
  # default: ZWxhc3RpYw== (elastic)
  ELASTIC_BOOTSTRAP_USER_B64: ZWxhc3RpYw==
  # Elasticsearch bootstrap user password
  # default: MkZlZGVyYXRlTTByZQ== (2FederateM0re)
  ELASTIC_BOOTSTRAP_PASSWORD_B64: MkZlZGVyYXRlTTByZQ==
  # Elasticsearch username
  # default: ZWxhc3RpYw== (elastic)
  ELASTIC_USER_B64: ZWxhc3RpYw==
  # Elasticsearch user password
  # default: MkZlZGVyYXRlTTByZQ== (2FederateM0re)
  ELASTIC_PASSWORD_B64: MkZlZGVyYXRlTTByZQ==
  # Logstash username
  # default: bG9nc3Rhc2hfc3lzdGVt (logstash_system)
  LOGSTASH_USER_B64: bG9nc3Rhc2hfc3lzdGVt
  # Logstash user password
  # default: MkZlZGVyYXRlTTByZQ== (2FederateM0re)
  LOGSTASH_PASSWORD_B64: MkZlZGVyYXRlTTByZQ==
  # Kibana username
  # default: a2liYW5h (kibana_system)
  KIBANA_USER_B64: a2liYW5hX3N5c3RlbQ==
  # Kibana user password
  # default: MkZlZGVyYXRlTTByZQ== (2FederateM0re)
  KIBANA_PASSWORD_B64: MkZlZGVyYXRlTTByZQ==