# p1as-self-service application settings
selfService:
  # Customization for p1as-self-service ingress resource
  ingress:
  # Customization for p1as-self-service service resource
  service:
  # Customization for p1as-self-service deployment resource
  deployment:
    # Replica count for pods
    replicaCount: 1
    # Resource limits for pods
    resources:
      limits:
        memory: 600Mi
        cpu:  400m
      requests:
        memory: 400Mi
        cpu: 200m
