# This defines the passwords required for root users of pingdirectory (used by the backup cron job)

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  root-user-password: MkZlZGVyYXRlTTByZQ==
  admin-user-password: MkZlZGVyYXRlTTByZQ==
  encryption-password: MkZlZGVyYXRlTTByZQ==
  PF_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque