# This defines the passwords required for root users of pingdirectory (used by the backup cron job)

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  root-user-password: MkZlZGVyYXRlTTByZQ==
  admin-user-password: MkZlZGVyYXRlTTByZQ==
  encryption-password: MkZlZGVyYXRlTTByZQ==
  PF_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==
  P14C_ENVIRONMENT_ID: cDE0Yy1lbnZpcm9ubWVudC1pZA==
  P14C_CLIENT_ID: cDE0Yy1jbGllbnQtaWQ=
  P14C_CLIENT_SECRET: cDE0Yy1jbGllbnQtc2VjcmV0

---

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque