kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/karpenter/bootstrap?ref=${K8S_GIT_BRANCH}
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/git-ops?ref=${K8S_GIT_BRANCH}
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager/base?ref=${K8S_GIT_BRANCH}
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/security?ref=${K8S_GIT_BRANCH}
- ping-cloud.yaml
- argocd-application-set.yaml

configMapGenerator:
- behavior: merge
  envs:
  - env_vars
  name: argocd-bootstrap
  namespace: argocd
  options:
    disableNameSuffixHash: true
patches:
- path: argocd-cm-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
    version: v1
- patch: argocd-strategic-patches.yaml
- patch: |-
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: argo-git-deploy
      namespace: argocd
    data:
      identity: |
        ${SSH_ID_KEY_BASE64}
