apiVersion: v1
kind: ConfigMap
metadata:
  name: pa-exporter-config
data:
  config.yml: |-
    ---
    metrics:
    - name: metric_pingaccess_response_concurrency_statistics_90_percentile
      path: $.items[*]."response.concurrency.statistics.90.percentile"+
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_statistics_count
      path: $.items[*]."response.statistics.count"+
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_time_statistics_90_percentile
      path: $.items[*]."response.time.statistics.90.percentile"+
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_concurrency_statistics_mean
      path: $.items[*]."response.concurrency.statistics.mean"+
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_time_statistics_mean
      path: $.items[*]."response.time.statistics.mean"+
      labels:
        environment: pingaccess
        source: heartbeat

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pa-collect-heartbeat
data:
  collect-heartbeat.sh: |-
    #!/bin/bash
    /usr/bin/json_exporter --config.file=/opt/config.yml --web.listen-address=":7979" &
    /usr/sbin/nginx -c /opt/nginx.conf
    while :
    do
      curl -k "https://localhost:$SERVICE_PORT/$SERVICE_SHORTNAME/heartbeat.ping" > /tmp/data/data.json
      sleep 5
    done

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pa-nginx-conf
data:
  nginx.conf: |-
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    include /etc/nginx/modules-enabled/*.conf;
    events {
        worker_connections 768;
    }
    http {
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        server {
            listen       8000;
            location / {
                root /tmp/data/;
            }
        }
        server {
            listen       8079;
            location / {
                proxy_pass http://localhost:7979/probe?target=http://localhost:8000/data.json;
            }
        }
    }

---