apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-pre-stop
data:
  pre-stop.sh: |-
    #!/bin/sh -x

    echo "Starting pre-stop hook"

    SHORT_HOST_NAME=$(hostname)
    ORDINAL=$(echo ${SHORT_HOST_NAME##*-})
    echo "Pod ordinal: ${ORDINAL}"

    NUM_REPLICAS=$(kubectl get statefulset "${K8S_STATEFUL_SET_NAME_PINGACCESS}" -o jsonpath='{.spec.replicas}')
    echo "Number of replicas: ${NUM_REPLICAS}"

    if test ${ORDINAL} -lt ${NUM_REPLICAS}; then
      echo "Not removing server since it is still in the topology"
      exit 0
    fi

    set +x
    # Retrieve Engine ID
    ENGINE_ID=$( curl -k --retry ${API_RETRY_LIMIT} \
                         --max-time ${API_TIMEOUT_WAIT} \
                         --retry-delay 1 \
                         --retry-connrefused \
                         -u ${PA_ADMIN_USER_USERNAME}:${PA_ADMIN_USER_PASSWORD} \
                         -H "X-Xsrf-Header: PingAccess " \
                         -X GET https://${K8S_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines | \
                         jq --arg SHORT_HOST_NAME "${SHORT_HOST_NAME}" \
                         '.items[] | select(.name==$SHORT_HOST_NAME) | .id' )

    # Delete Engine
    curl -k --retry ${API_RETRY_LIMIT} \
                         --max-time ${API_TIMEOUT_WAIT} \
                         --retry-delay 1 \
                         --retry-connrefused \
                         -u ${PA_ADMIN_USER_USERNAME}:${PA_ADMIN_USER_PASSWORD} \
                         -H "X-Xsrf-Header: PingAccess " \
                         -X DELETE https://${K8S_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines/${ENGINE_ID} \
                         > /dev/null
    set -x