apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-pre-stop
data:
  pre-stop.sh: |-
    #!/bin/sh -x

    . "${HOOKS_DIR}/utils.lib.sh"

    echo "Starting pre-stop hook"

    SHORT_HOST_NAME=$(hostname)
    ORDINAL=$(echo ${SHORT_HOST_NAME##*-})
    echo "Pod ordinal: ${ORDINAL}"

    NUM_REPLICAS=$(kubectl get statefulset "${K8S_STATEFUL_SET_NAME_PINGACCESS}" -o jsonpath='{.spec.replicas}')
    echo "Number of replicas: ${NUM_REPLICAS}"

    if test ${ORDINAL} -lt ${NUM_REPLICAS}; then
      echo "Not removing server since it is still in the topology"
      exit 0
    fi

    # Retrieve Engine ID
    ENGINE_ID=$( make_api_request -X GET https://${K8S_STATEFUL_SET_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines | \
                jq --arg SHORT_HOST_NAME "${SHORT_HOST_NAME}" \
                '.items[] | select(.name==$SHORT_HOST_NAME) | .id' )

    # Delete Engine
    make_api_request -X DELETE https://${K8S_STATEFUL_SET_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines/${ENGINE_ID} \
    > /dev/null