kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Pingdirectory
# Create the config maps that hold the variable for triggering updates of PD servers
- name: pingdirectory-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdirectory/env_vars

# Merge all env_vars into Pingdirectory common environment variables configmap
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdirectory/env_vars


# PingCloud services
# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars

# PingCloud-oauth
- name: p14c-oauth-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud BOM service
- name: p14c-bom-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

patchesStrategicMerge:

### Regional enablement - remove admins, backups, etc. from secondary ###
### This patch should be commented out on the primary region ###
- ../base/ping-cloud/remove-from-secondary-patch.yaml
