kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- private
- public

patchesStrategicMerge:
### P14C Bootstrap service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: nginx-ingress-serviceaccount
    annotations:
      ${IRSA_INGRESS_ANNOTATION_KEY_VALUE}
