kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/logging?ref=${K8S_GIT_BRANCH}
- ${DASH_REPO_URL}/os-dashboards?ref=${DASH_REPO_BRANCH}


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- behavior: merge
  envs:
  - env_vars
  name: elk-environment-variables
- behavior: merge
  literals:
  - SERVICE_SSM_PATH_PREFIX=${SERVICE_SSM_PATH_PREFIX}
  - REGION=${REGION}
  name: logging-bootstrap-environment-variables
- behavior: merge
  files:
  - notifications/sns.json
  name: os-notifications-channels


### enrichment-bootstrap service account ###


patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: opensearch.${DNS_ZONE}
  target:
    kind: Service
    name: opensearch-cluster-headless
    namespace: elastic-stack-logging
    version: v1
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-info
    data:
      cluster.name: ${CLUSTER_NAME}
      logs.region: ${REGION}
      tenant_domain: ${TENANT_DOMAIN}
      primary_tenant_domain: ${PRIMARY_TENANT_DOMAIN}
      newrelic_cluster_name: ${NEW_RELIC_ENVIRONMENT_NAME}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: enrichment
      name: enrichment
      annotations:
        purpose: service-account-for-ping-cloud-stack
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
