# NOTE: unlike the rest of this directory, this file is managed by Ping
# The rest of this directory is a direct copy of https://github.com/CrunchyData/postgres-operator-examples
# TODO: potentially fork so not in repo??
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

  # TODO: just the default PGO namespace for now
resources:
- namespace
- default

images:
- name: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/postgres-operator
- name: registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade
  newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/postgres-operator-upgrade

# Patch the CRDs such that argocd will sync them properly
patches:
- patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "Replace=true"
  target:
    kind: CustomResourceDefinition
    name: postgresclusters.postgres-operator.crunchydata.com
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "Replace=true"
  target:
    kind: CustomResourceDefinition
    name: pgupgrades.postgres-operator.crunchydata.com
    version: v1
