apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
spec:
  template:
    spec:
      containers:
      - name: pingaccess-admin
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "2"
