kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ./secret/secret.yaml
- ./storage/storage.yaml
- ./statefulset/statefulset.yaml
- ./service/service.yaml
- ./periodic-backup/periodic-backup.yaml

commonLabels:
  role: pingdirectory

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  env: ./env/env_vars

vars:
- name: K8S_STATEFUL_SET_NAME
  objref:
    kind: StatefulSet
    name: ds
    apiVersion: apps/v1
- name: K8S_STATEFUL_SET_SERVICE_NAME
  objref:
    kind: Service
    name: pingdirectory
    apiVersion: v1