kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ./secret/secret.yaml
- ./storage/storage.yaml
- ./statefulset/statefulset.yaml
- ./service/service.yaml
- ./periodic-backup/periodic-backup.yaml

commonLabels:
  role: pingdirectory

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  env: ./env/env_vars

vars:
- name: K8S_STATEFUL_SET_NAME
  objref:
    kind: StatefulSet
    name: ds
    apiVersion: apps/v1
- name: K8S_STATEFUL_SET_SERVICE_NAME
  objref:
    kind: Service
    name: pingdirectory
    apiVersion: v1

patches:
- target:
    kind: StatefulSet
    name: ds
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value: [{"name":"K8S_STATEFUL_SET_NAME","value":"$(K8S_STATEFUL_SET_NAME)"},{"name":"K8S_STATEFUL_SET_SERVICE_NAME","value":"$(K8S_STATEFUL_SET_SERVICE_NAME)"},{"name":"MAX_HEAP_SIZE","value":"4g"},{"name":"UNBOUNDID_JAVA_ARGS","value":"-client -Xmx4g -Xms4g"}]
- target:
    kind: StatefulSet
    name: ds
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value: [{"name":"out-dir","mountPath":"/opt/out"}]
- target:
    kind: StatefulSet
    name: ds
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value: [{"name":"out-dir","persistentVolumeClaim":{"claimName":"out-dir"}}]
- target:
    kind: StatefulSet
    name: ds
  patch: |-
    - op: add
      path: /spec/volumeClaimTemplates
      value: [{"metadata":{"name":"out-dir"},"spec":{"accessModes":["ReadWriteOnce"],"storageClassName":"pingdirectory-gp2","resources":{"requests":{"storage":"20Gi"}}}}]
