kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# Deploy the CD tool
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/git-ops?ref=${K8S_GIT_BRANCH}

# Deploy cert-manager as part of the bootstrap process so that it's running before its CRD resources are created
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/cert-manager/base?ref=${K8S_GIT_BRANCH}

# Deploy sealed-secrets controller so it's up and ready before ping-cloud namespace is created
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/security?ref=${K8S_GIT_BRANCH}

# Deploy the CD application
- argo-application.yaml

generatorOptions:
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active

secretGenerator:
- name: sealed-secrets-key
  namespace: kube-system
  behavior: create
  files:
  - tls.crt
  - tls.key
  type: "kubernetes.io/tls"

patchesStrategicMerge:

### Git auth credential to the cluster state repo ###
- |-
  apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: argo-git-deploy
    namespace: argocd
  data:
    GIT_AUTH_CRED: ${GIT_AUTH_CRED_BASE64}

patchesJson6902:

### Cluster state repo URL for the CD tool ###
- target:
    version: v1
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
  patch: |-
    - op: replace
      path: /data/repositories/0/url
      value: ${CLUSTER_STATE_REPO_URL}

### Cluster state repo URL for the CD tool ###
#- target:
#    version: v1
#    kind: ConfigMap
#    name: argocd-cm
#    namespace: argocd
#  patch: |
#    - op: replace
#      path: /data/repositories
#      value:
#        - url: ${CLUSTER_STATE_REPO_URL}
#          passwordSecret:
#            name: argo-git-deploy
#            key: GIT_USER
#          usernameSecret:
#            name: argo-git-deploy
#            key: GIT_PASS