kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingcommon
- pingdirectory/config
- pingaccess-was/config
- pingaccess-was/ff-external-ingress
- pingaccess/config
- pingfederate/config
- pingdelegator/config
- pingdatasync/config
- pingfederate/provisioning
- granular-updates

configMapGenerator:
- behavior: merge
  files:
  - descriptor.json
  name: topology-descriptor

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: known-hosts-config
    data:
      known_hosts: |
        ${KNOWN_HOSTS_CLUSTER_STATE_REPO}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ping-serviceaccount
      annotations:
        purpose: service-account-for-ping-cloud-stack
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingdirectory-ops-serviceaccount
      annotations:
        purpose: service-account-for-ping-directory-ops
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingaccess-serviceaccount
      annotations:
        purpose: service-account-for-ping-access
        ${IRSA_PA_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingdirectory-serviceaccount
      annotations:
        purpose: service-account-for-ping-directory
        ${IRSA_PD_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingfederate-serviceaccount
      annotations:
        purpose: service-account-for-ping-federate
        ${IRSA_PF_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingfederate-admin-serviceaccount
      annotations:
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: p14c-bootstrap-serviceaccount
      annotations:
        purpose: service-account-for-ping-cloud-stack
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
