kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# NOTE: remove '[]' when enabling resources below. Latest Kustomize version does not allow completely empty 
# kustomization.yaml files.
resources: []

### Feature flag - Uncomment this section to enable Postgres Operator (PGO)
# - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/pgo/base?ref=${K8S_GIT_BRANCH}