apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml

configMapGenerator:
- name: cwagentconfig
  namespace: amazon-cloudwatch
  behavior: merge
  files:
    - cwagentconfig.json
    - prometheus.yaml

patchesStrategicMerge:
  - delete-daemonset.yaml

patches:
  - target:
      version: apps/v1
      kind: Deployment
      name: kube-state-metrics
      namespace: kube-system
    path: kube-state-metrics.yaml