apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml

configMapGenerator:
- name: cwagentconfig
  namespace: amazon-cloudwatch
  behavior: merge
  files:
    - cwagentconfig.json
    - prometheus.yaml

patchesStrategicMerge:
  - delete-daemonset.yaml

patches:
  - target:
      kind: Deployment
      namespace: kube-system
      name: kube-state-metrics
    patch: |-
      - op: merge
        path: /spec/template/spec/containers/0/args/-
        value:
          - --resources=persistentvolumeclaims,persistentvolumes,pods,nodes,endpoints
          - --namespaces-denylist=default, health, kube-node-lease, kube-public, kube-system, pod-reaper, newrelic