apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "appset-example"
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ${CLUSTER_STATE_REPO_BRANCH}
    argocd-image-updater.argoproj.io/image-list: ${IMAGE_LIST}
    argocd-image-updater.argoproj.io/apps.update-strategy: latest
    argocd-image-updater.argoproj.io/apps.allow-tags: regexp:^${IMAGE_TAG_PREFIX}.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh-key
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ${SLACK_CHANNEL}
spec:
  generators:
    - git:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        revision: ${CLUSTER_STATE_REPO_BRANCH}
        directories:
          - path: k8s-configs/${REGION_NICK_NAME}/*
  template:
    metadata:
      name: '{{path.basename}}-${REGION_NICK_NAME}'
    spec:
      project: default
      source:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
        path: '{{path}}'
        plugin:
          name: git-ops-command
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: batch
          kind: Job
          jsonPointers:
            - /spec/ttlSecondsAfterFinished
      syncPolicy:
        automated:
          prune: true
