kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcloud-metadata-environment-variables

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
