apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingentitlement
  labels:
    app: ping-cloud
spec:
  replicas: 1
  template:
    spec:
      serviceAccount: ping-serviceaccount
      containers:
      - name: pingcloud-oauth
        image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-tools/entitlement:v1.0.0-pdo-1776-entitlement-image
      command:
      - python3
      - src/OAuthClientServicesController.py
      envFrom:
      - configMapRef:
          name: pingcloud-oauth-environment-variables
      - secretRef:
          name: p14c-bootstrap-secret
      env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace