# This will be dynamic eventually
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: p14c-bootstrap-secrets
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  P14C_ENVIRONMENT_ID: MDUxOGFlMzAtNDA1ZC00MGE2LThlZDEtOTg1ZDIyMzFkNmVk
  P14C_TOKEN_ENDPOINT: aHR0cHM6Ly9hdXRoLnBpbmdvbmUuY29tLzA1MThhZTMwLTQwNWQtNDBhNi04ZWQxLTk4NWQyMjMxZDZlZC9hcw==
  P14C_CLIENT_ID: N2RjNzA3ZGItZTU1Yi00OTgyLTg4ZGMtOGQ2OWRiZmE0MDYx
  P14C_CLIENT_SECRET: fjlaWUZMTndUZy1lLk4yRmROdzU2Y3VVNGtkVEIwVUNzLUlNOWxnTDAuQXh5aEh6RGtYVHl2T21qWVhGdzd1Zw==