apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: devops-secret
  annotations:
    sealedsecrets.bitnami.com/managed: "true"

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  PF_LDAP_PASSWORD: ${GENERATED_LDAP_PASSWORD_BASE64}
  PF_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
