# This job copies NR License key secret object to 'newrelic' namespace
---
apiVersion: batch/v1
kind: Job
metadata:
  name: newrelic-license-secret-exporter
  namespace: newrelic
  labels:
    app: newrelic-license-secret-exporter
spec:
  template:
    metadata:
      labels:
        app: newrelic-license-secret-exporter
      annotations: {}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: nri-bundle-newrelic-infrastructure
      containers:
      - name: newrelic-license-secret-exporter
        image: public.ecr.aws/r2h3l6e4/bitnami/kubectl:1.15.3
        command: [ "/bin/sh", "-c" ]
        args: [ "kubectl get secret $(SECRET_NAME) --namespace=$(SECRET_NAMESPACE) -oyaml | sed 's|namespace: .*|namespace: $(CURRENT_NAMESPACE)|' | kubectl apply --namespace=$(CURRENT_NAMESPACE) -f -" ]
        env:
          - name: "SECRET_NAME"
            value: "newrelic-license-key"
          - name: "SECRET_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SECRET_NAMESPACE']
          - name: "CURRENT_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace