# Source: p1as-newrelic/charts/nri-bundle/charts/nri-metadata-injection/templates/admission-webhooks/job-patch/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-nri-metadata-injection-admission
  namespace: newrelic
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: nri-metadata-injection-admission
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nri-metadata-injection
    app.kubernetes.io/version: 1.27.2
    helm.sh/chart: nri-metadata-injection-4.19.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-nri-metadata-injection-admission
subjects:
  - kind: ServiceAccount
    name: release-name-nri-metadata-injection-admission
    namespace: newrelic
