### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-environment-variables
  namespace: ping-cloud

---

# PDO-6441: Disable Cert Manager ClusterIssuer preferredChain
# The preferredChain will deploy as an empty string
# This workaround is for the cert-manager defect: https://github.com/cert-manager/cert-manager/pull/6755#issuecomment-1944231410
# Cert manager is still working on a formal fix. Once this is resolved we can revert and will need to upgrade cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    preferredChain: null