kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- git-ops
- cert-manager
- cluster-autoscaler
- efs-driver
- service-discovery
- ingress
- logging
- metrics
- monitoring
- security
- pod-reaper
- health
# TODO: somehow show that this is being toggled in code...
- pgo
