kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../../../k8s-configs/ping-cloud/base/pingfederate/engine/cloud-generic/ff-radius-proxy

# Removed because this is not added for CDEs
# configMapGenerator:
#   - name: pingcloud-radsecproxy-environment-variables
#     behavior: merge
#     envs:
#     - ../../env_vars