kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1


# PingCloud common resources and configs. These should always be included. DO NOT comment them out.
resources:
- pingcommon
- pingcentral
- pingaccess-was/config
- pingaccess-was/admin
- pingaccess-was/engine
- pingaccess-was/ff-external-ingress

configMapGenerator:
- behavior: merge
  files:
  - descriptor.json
  name: topology-descriptor

patches:
- patch: pingaccess-was/ff-external-ingress/remove-external-ingress.yaml
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: known-hosts-config
    data:
      known_hosts: |
        ${KNOWN_HOSTS_CLUSTER_STATE_REPO}
- patch: "apiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: ping-serviceaccount\n
    \ annotations:\n    purpose: service-account-for-ping-cloud-stack\n    ${IRSA_PING_ANNOTATION_KEY_VALUE}\n
    \   "
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pingdirectory-ops-serviceaccount
      annotations:
        purpose: service-account-for-ping-directory-ops
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: p14c-bootstrap-serviceaccount
      annotations:
        purpose: service-account-for-ping-cloud-stack
        ${IRSA_PING_ANNOTATION_KEY_VALUE}
