apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess
spec:
  template:
    spec:
      containers:
      - name: pingaccess
        resources:
          requests:
            memory: 3Gi
            cpu: 1
          limits:
            memory: 3Gi
            cpu: 1