# Add an "argocd" Namespace for all namespace-scoped resources
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Add a configmap for Argo to use to configure itself
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-bootstrap
  namespace: argocd
---
# Add the plugin configuration file in the sidecar
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-ops-command-plugin-cm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: git-ops-command
    spec:
      generate:
        command: [ "git-ops-command.sh" ]
