apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-admin-periodic-csd-upload
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingaccess-was-admin-periodic-csd-upload
            image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingaccess:6.1.3-v1.0.0
            # Required because new GSA images run as non-root by default, and P1AS does not work with non-root user yet.
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
            command:
            - /opt/in/backup-csd-data.sh
            env:
            - name: CSD_POD_ROLE
              value: "pingaccess-was-admin"
            - name: CSD_CONTAINER_NAME
              value: "pingaccess-was-admin"
            envFrom:
            - configMapRef:
                name: pingaccess-was-environment-variables
            volumeMounts:
            - name: pingaccess-periodic-csd-upload
              mountPath: /opt/in/backup-csd-data.sh
              subPath: backup-csd-data.sh
          volumes:
          - name: pingaccess-periodic-csd-upload
            configMap:
              name: pingaccess-periodic-csd-upload
              defaultMode: 0555
