kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- config
- admin
- engine
# TODO: figure out what to do with this provisioning
# Provisioning, while added here, is manually uncommented only if enabled
#- ff-provisioning