kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- prometheus-job-exporter.yaml
- alertmanager.yaml
- dashboards

configMapGenerator:
- name: prometheus-environment-variables
  envs:
    - env_vars

- name: default-prom-alerts
  envs:
    - prometheus-alerts.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: prometheus
      namespace: prometheus
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: defaultalertsconfig
          configMap:
            name: default-prom-alerts
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: defaultalertsconfig
          mountPath: /etc/prometheus/alert-rules.d
