kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
  - apiservers-service-monitor.yaml
  - cadvisor-service-monitor.yaml
  - generic-pod-monitor.yaml
  - generic-service-monitor.yaml
  - ksm-service-monitor.yaml
  - nodes-service-monitor.yaml
  - pgo-pod-monitor.yaml
  - prometheus-agent.yaml
  - prometheus-scrape-config.yaml
  - prometheus-service.yaml
  - rbac.yaml
  - storage.yaml
  - volume-autoscaler
  - prometheus-job-exporter.yaml
  - thanos/thanos.yaml
  - thanos/thanos-objstore-config.yaml

images:
  - name: docker.io/bitnami/thanos
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/thanos

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-environment-variables
    envs:
      - env_vars