kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- prometheus-job-exporter.yaml
- alertmanager.yaml
- prometheus-config.yaml
- prometheus-agent-config.yaml
- prometheus-agent.yaml
- https://github.com/pingidentity/ping-cloud-dashboards/grafana?ref=v1.17-release-branch

configMapGenerator:
- name: prometheus-environment-variables
  envs:
    - env_vars

- name: prom-alerts
  files:
   - default-rule.yml