apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
<<<<<<< HEAD
  namespace: prometheus
  labels:
    app: prometheus-agent
=======
>>>>>>> v2.0-release-branch
spec:
  containers:
    - name: prometheus
      envFrom:
        - configMapRef:
            name: prometheus-environment-variables
  scrapeInterval: 30s
  scrapeTimeout: 5s
  externalLabels:
    k8s_cluster_name: ${CLUSTER_NAME}-${TENANT_NAME}-${REGION_NICK_NAME}
  scrapeConfigSelector:
    matchLabels:
<<<<<<< HEAD
      app: prometheus-agent
  template:
    metadata:
      labels:
        app: prometheus-agent
    spec:
      serviceAccountName: prometheus
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: prometheus
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/prom/prometheus:v2.47.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.enable-lifecycle"
          - "--enable-feature=agent"
          - "--enable-feature=expand-external-labels"
        envFrom:
          - configMapRef:
              name: prometheus-environment-variables
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 500m
            memory: 4000Mi
          requests:
            cpu: 100m
            memory: 512Mi
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-agent-config


---
=======
      prometheus: system-monitoring-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: agent
  podMonitorSelector:
    matchLabels:
      prometheus: agent
  remoteWrite:
    - url: 'http://prometheus:9090/api/v1/write'
  enableFeatures:
    - agent
    - expand-external-labels
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  serviceAccountName: prometheus
  image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/prom/prometheus:v2.47.0
  resources:
    limits:
      cpu: 500m
      memory: 4000Mi
    requests:
      cpu: 100m
      memory: 512Mi
>>>>>>> v2.0-release-branch
