kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: default

helmCharts:
  - name: p1as-beluga-tools
    includeCRDs: false
    valuesInline:
      minecraftServer:
        eula: true
        difficulty: hard
        rcon:
          enabled: true
    releaseName: p1as-beluga-tools
    version: ~18.0.0-PDO-5322
    repo:  oci://705370621539.dkr.ecr.us-west-2.amazonaws.com/p1as-beluga-tools