apiVersion: v1
kind: Secret
metadata:
  name: argo-git-deploy
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/abhalla-cluster-development-cluster-state-repo
  type: git
  sshPrivateKey: |
    ${SSH_ID_KEY_BASE64}