kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/git-ops?ref=${K8S_GIT_BRANCH}
- argocd-application-set.yaml

configMapGenerator:
- behavior: merge
  envs:
  - env_vars
  name: argocd-bootstrap
  namespace: argocd
  options:
    disableNameSuffixHash: true
patches:
- path: argocd-cm-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
    version: v1
- path: argocd-strategic-patches.yaml
