kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources:
  - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/git-ops?ref=${K8S_GIT_BRANCH}
  - argocd-application-set.yaml

patchesStrategicMerge:
  - argocd-strategic-patches.yaml

patchesJson6902:
  ### Cluster state repo URL and auth configuration for the CD tool ###
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: argocd-cm-patch.yaml

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: argocd-ui-ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: argocd.${DNS_ZONE}
      - op: replace
        path: /spec/rules/0/host
        value: argocd.${DNS_ZONE}

configMapGenerator:
  - name: argocd-bootstrap
    namespace: argocd
    behavior: merge
    envs:
      - env_vars
    options:
      disableNameSuffixHash: true
