# This defines the pingaccess-was engine deployment.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  labels:
    cluster: pingaccess-was-cluster
    role: pingaccess-was-engine
spec:
  selector:
    matchLabels:
      role: pingaccess-was-engine
  replicas: 1
  serviceName: pingaccess-was
  podManagementPolicy: OrderedReady
  template:
    metadata:
      name: pingaccess-was-engine
      labels:
        cluster: pingaccess-was-cluster
        role: pingaccess-was-engine
      annotations:
        lastUpdateReason: "NA"
    spec:
      serviceAccount: ping-serviceaccount
      affinity:
        podAntiAffinity:
          # Add a soft requirement for each PA runtime pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - pingaccess-was-engine
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      initContainers:
      - name: profile-init
        image: public.ecr.aws/r2h3l6e4/pingcloud-profiles/pingaccess-was:${PINGACCESS_WAS_PROFILE_IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - |
            cp -r /opt/stage/* /opt/in/
            chmod a+x /opt/in/hooks/*
        envFrom:
          - configMapRef:
              name: pingaccess-environment-variables
        volumeMounts:
          - name: in-dir
            mountPath: /opt/in
      - name: pingaccess-was-init
        # FIXME: switch to same user as app
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        image: pingcloud-mirror.jfrog.io/bitnami/kubectl:1.15.3
        imagePullPolicy: IfNotPresent
        command:
        - /copy-dependencies.sh
        volumeMounts:
        - name: ssh-dir
          mountPath: /.ssh
        - name: data-dir
          mountPath: /data
        - name: in-dir
          mountPath: /opt/in
        - name: ssh-id-key-secret
          mountPath: /id_rsa
          subPath: id_rsa
        - name: known-hosts-config
          mountPath: /known_hosts
          subPath: known_hosts
        - name: pingaccess-was-init
          mountPath: /copy-dependencies.sh
          subPath: copy-dependencies.sh
        - name: pingaccess-was-init
          mountPath: /utils.lib.sh
          subPath: utils.lib.sh
        envFrom:
        - configMapRef:
            name: pingaccess-was-environment-variables
      - name: wait-for-services
        # FIXME: switch to same user as app
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        image: pingcloud-mirror.jfrog.io/busybox:1.32
        imagePullPolicy: IfNotPresent
        command:
        - /wait-for-services.sh
        volumeMounts:
        - name: pingaccess-was-init
          mountPath: /utils.lib.sh
          subPath: utils.lib.sh
        - name: pingaccess-was-init
          mountPath: /wait-for-services.sh
          subPath: wait-for-services.sh
        envFrom:
        - configMapRef:
            name: pingaccess-was-environment-variables
      containers:
      - name: pingaccess-was
        image: pingcloud-virtual.jfrog.io/pingidentity/pingaccess:${PINGACCESS_IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "20m"
          limits:
            memory: "1280Mi"
            cpu: 1
        volumeMounts:
        # FIXME: fix home directory when containers run as non-root user
        - name: ssh-dir
          mountPath: /root/.ssh
        - name: topology-descriptor
          mountPath: /opt/staging/topology/descriptor.json
          subPath: descriptor.json
        - name: data-dir
          mountPath: /usr/local/bin/kubectl
          subPath: kubectl
        - name: data-dir
          mountPath: /usr/local/bin/skbn
          subPath: skbn
        - name: pingaccess-was-license
          mountPath: /opt/in/instance/conf/pingaccess.lic
          subPath: pingaccess.lic
        - name: data-dir
          mountPath: /opt/staging/ds_env_vars
          subPath: ds_env_vars
        - name: in-dir
          mountPath: /opt/in
        readinessProbe:
          exec:
            command: [ /opt/staging/hooks/99-pa-was-engine-liveness.sh ]
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: [ /opt/staging/hooks/99-pa-was-engine-liveness.sh ]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/staging/hooks/86-pre-stop.sh
        ports:
        - containerPort: 3000
        env:
        - name: OPERATIONAL_MODE
          value: CLUSTERED_ENGINE
        - name: PA_ADMIN_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pingaccess-was-passwords
              key: PA_ADMIN_USER_PASSWORD
        envFrom:
        - configMapRef:
            name: pingaccess-was-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
      volumes:
      - name: ssh-dir
        emptyDir: {}
      - name: data-dir
        emptyDir: {}
      - name: in-dir
        emptyDir: {}
      - name: pingaccess-was-init
        configMap:
          name: pingcommon-init
          defaultMode: 0555
      - name: topology-descriptor
        configMap:
          name: topology-descriptor
          optional: true
          defaultMode: 0644
      - name: ssh-id-key-secret
        secret:
          secretName: ssh-id-key-secret
          optional: true
          defaultMode: 0400
      - name: known-hosts-config
        configMap:
          name: known-hosts-config
          optional: true
          defaultMode: 0644
      - name: pingaccess-was-license
        secret:
          secretName: pingaccess-was-license
          optional: true
          defaultMode: 0400
      - name: pingaccess-was-passwords
        secret:
          secretName: pingaccess-was-passwords
          optional: true
          defaultMode: 0400
