kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ${PING_CLOUD_NAMESPACE}

resources:
  - ../base
  - custom-resources

helmCharts:
  - name: p1as-pingdirectoryproxy
    additionalValuesFiles:
      - ../../values-files/base/values.yaml   # base values.yaml
      - ../../values-files/us-west-2/values.yaml   # regional values.yaml
      - values.yaml   # app specific values.yaml
    version: v2.0-hackathon-2024
    valuesInline:
      ecrRegistryName: "705370621539.dkr.ecr.us-west-2.amazonaws.com/dev"
    repo: oci://705370621539.dkr.ecr.us-west-2.amazonaws.com/dev/p1as-pingdirectoryproxy  
    # repo: oci://${ECR_REGISTRY_NAME}/dev/p1as-pingdirectoryproxy
    
### This field is used to trigger a resync of the p1as-pingdirectoryproxy helm chart ###
configMapGenerator:
  - name: last-update-reason
    literals:
      - UPDATE_REASON=""

patchesStrategicMerge:
  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
  - custom-patches.yaml