pingdirectoryproxy:
  # PingDirectoryProxy statefulset
  statefulSet:
    metadata:
      name: pingdirectoryproxy
      labels:
        class: pingdirectoryproxy
    serviceName: pingdirectoryproxy
    # set container limits
    serviceAccountName: ping-serviceaccount
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "4Gi"
        cpu: "2"