kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Apply pingdatasync deployment resources
resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingdatasync/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingdatasync${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingdatasync${ECR_ENV}
  newTag: ${PINGDATASYNC_IMAGE_TAG}

# pingdatasync admin
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingdatasync-last-update-config
  target:
    group: apps
    kind: StatefulSet
    name: pingdatasync
    version: v1
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdatasync-admin.${DNS_ZONE}
  target:
    kind: Service
    name: pingdatasync-admin
    version: v1
